import {JSDOM} from 'jsdom';
import {afterEach,test} from 'node:test';
import assert from 'node:assert/strict';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'http://localhost/'});
for(const key of ['window','document','HTMLElement','HTMLDialogElement','MutationObserver','Node','Event','MouseEvent','CustomEvent'])Object.defineProperty(globalThis,key,{value:(dom.window as any)[key],configurable:true,writable:true});
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
(globalThis as any).IS_REACT_ACT_ENVIRONMENT=true;
(globalThis as any).EventSource=class{addEventListener(){}close(){}};
dom.window.HTMLElement.prototype.scrollIntoView=function(){};
dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;};
const React=await import('react');
const {render,fireEvent,screen,waitFor,cleanup,within}=await import('@testing-library/react');
const {App}=await import('../src/App');
const originalFetch=globalThis.fetch;
afterEach(()=>{cleanup();globalThis.fetch=originalFetch;});
const json=(value:unknown)=>new Response(JSON.stringify(value),{status:200,headers:{'Content-Type':'application/json'}});

test('one viewer switches understanding, scenarios, draft and review without approving or changing the draft',async()=>{
 const calls:{path:string;body:any}[]=[];
 const analysis={id:'analysis',type:'analysis',title:'需求理解',revision:1,items:[{id:'R1',title:'需求节点',description:'用户可以登录'}]};
 const scenes={id:'scenes',type:'scenarios',title:'测试场景',revision:1,items:[{id:'S1',title:'场景节点',requirement_ids:['R1'],description:'成功登录'}]};
 const draft={id:'cases',type:'cases',title:'测试用例',revision:1,items:[{id:'TC1',title:'草稿用例',scenario_id:'S1',steps:[{action:'登录',expected:'成功'}]}]};
 const reviewed={...draft,revision:2,items:[{...draft.items[0],title:'评审后的用例'}]};
 const catalog=[{...analysis,label:'需求理解',phase:'understood'},{...scenes,label:'测试场景',phase:'scenarios_generated'},{...draft,label:'用例草稿',phase:'cases_generated'},{...reviewed,label:'评审结果',phase:'reviewed'}].map(value=>({...value,artifact_id:value.id,key:value.id+':'+value.revision,is_current:value.id!=='cases'||value.revision===2}));
 const prompt={id:'confirm-review:2',kind:'case_result_review',title:'确认评审结果',message:'确认后完成',review:{summary:'检查完成',issues:[]}};
 const state={chat:{id:'chat',project_id:'project',title:'登录测试'},sources:[],messages:[{id:'assistant',role:'assistant',content:'评审完成。',metadata:{artifact_ids:['analysis','scenes','cases'],artifact_revisions:{analysis:1,scenes:1,cases:2}}}],runs:[{id:'run',status:'waiting',mode:'hitp',stage:'case_result_review',artifact_ids:['analysis','scenes','cases'],updated_at:'2026-09-13T00:00:00Z'}],conversation_prompt:prompt};
 globalThis.fetch=(async(input:any,init:RequestInit={})=>{const path=String(input).replace(/^\/api/,''),body=init.body?JSON.parse(String(init.body)):undefined;calls.push({path,body});
  if(path==='/projects')return json([{id:'project',name:'测试项目'}]);
  if(path==='/settings')return json({model:'mock'});
  if(path==='/projects/project/profiles')return json([{id:'profile',name:'Default',version:1,config:{}}]);
  if(path==='/projects/project/chats')return json([state.chat]);
  if(path==='/chats/chat')return json(state);
  if(path==='/chats/chat/artifacts')return json({items:catalog});
  if(path==='/artifacts/analysis')return json(analysis);
  if(path==='/artifacts/scenes')return json(scenes);
  if(path==='/artifacts/cases')return json(reviewed);
  if(path==='/artifacts/cases/revisions/1')return json(draft);
  if(path==='/artifacts/cases/revisions/2')return json(reviewed);
  if(path==='/artifacts/analysis/revisions/1')return json(analysis);
  if(path==='/artifacts/scenes/revisions/1')return json(scenes);
  if(path==='/chats/chat/turns')return json({id:'turn',status:'succeeded',message:'已确认',parts:[],pending:[],actions:[]});
  if(path.endsWith('/workspace')||path.endsWith('/workspace-state'))return json({});
  return json([]);
 }) as typeof fetch;
 render(<App/>);
 const open=await screen.findByRole('button',{name:'查看当前成果'});
 fireEvent.change(screen.getByLabelText('聊天输入'),{target:{value:'尚未发送的补充意见'}});
 fireEvent.click(open);
 let viewer=await screen.findByRole('dialog',{name:/查看成果/});
 const picker=await within(viewer).findByLabelText('切换过程成果');
 await waitFor(()=>assert.equal((picker as HTMLSelectElement).disabled,false));
 for(const [value,text] of [['analysis:1','需求节点'],['scenes:1','场景节点'],['cases:1','草稿用例'],['cases:2','评审后的用例']]){
  fireEvent.change(picker,{target:{value}});
  await screen.findByText(text);
 }
 assert.equal(calls.filter(call=>call.body).length,0);
 assert.ok(calls.some(call=>call.path==='/artifacts/cases/revisions/1'));
 viewer=screen.getByRole('dialog',{name:/查看成果/});
 assert.ok(within(viewer).getByRole('button',{name:'导出 Excel'}));
 fireEvent.click(within(viewer).getByRole('button',{name:'返回对话'}));
 assert.equal((screen.getByLabelText('聊天输入') as HTMLTextAreaElement).value,'尚未发送的补充意见');
 fireEvent.click(screen.getByRole('button',{name:'确认评审建议并修改用例'}));
 await waitFor(()=>assert.equal(calls.filter(call=>call.path==='/chats/chat/turns').length,1));
 assert.equal(calls.find(call=>call.path==='/chats/chat/turns')!.body.reply_to,prompt.id);
});
