import type {CSSProperties} from 'react';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowUp,ChevronDown,FileText,Folder,Link,Menu,MessageSquare,Paperclip,Plus,Settings as SettingsIcon,X} from 'lucide-react';
import {api,errText} from './api';
import {ArtifactWorkspace} from './ArtifactWorkspace';
import {ArtifactCard} from './ArtifactCard';
import {SettingsDialog} from './SettingsDialog';
import {SourcesDialog} from './SourcesDialog';
import {MemoryDialog} from './MemoryDialog';
import {RunCard} from './RunCard';
import {RunTimeline} from './RunTimeline';
import {Dialog,ErrorBox,Logo,Spinner} from './ui';
import {useDrafts} from './useDrafts';
import {busy,intents,roles,depthNames} from './types';
import type {Artifact,Chat,Depth,Json,Profile,Project,Settings,Snapshot} from './types';

export function App(){
 const [openedArtifact,setOpenedArtifact]=useState<Artifact>();
 const [workspaceOpen,setWorkspaceOpen]=useState(false);const [workspaceWidth,setWorkspaceWidth]=useState(42);
 const [settingsTab,setSettingsTab]=useState<'model'|'profile'>('model');const [runOverride,setRunOverride]=useState<Json>();
 const [mobilePanel,setMobilePanel]=useState<'results'|'chat'>('chat');
 const [optionsOpen,setOptionsOpen]=useState(false);const [depth,setDepth]=useState<Depth>('auto');const [mode,setMode]=useState<'auto'|'hitp'>('auto');const [caseTypes,setCaseTypes]=useState(['Business','Negative','Boundary']);const [caseTypesTouched,setCaseTypesTouched]=useState(false);
 const [projectLoading,setProjectLoading]=useState(true);const [projects,setProjects]=useState<Project[]>([]);const [projectId,setProjectId]=useState('');const [chats,setChats]=useState<Chat[]>([]);const [profiles,setProfiles]=useState<Profile[]>([]);const [profileId,setProfileId]=useState('');
 const [chatId,setChatId]=useState('');const [snapshot,setSnapshot]=useState<Snapshot>();const [intent,setIntent]=useState('auto');
 const [artifactEpoch,setArtifactEpoch]=useState(0);const [settings,setSettings]=useState<Settings>();const [settingsOpen,setSettingsOpen]=useState(false);const [sourcesOpen,setSourcesOpen]=useState(false);const [memoryOpen,setMemoryOpen]=useState(false);const [proposal,setProposal]=useState<Json>();
 const [projectDialog,setProjectDialog]=useState(false);const [projectName,setProjectName]=useState('');const [sidebar,setSidebar]=useState(false);const [error,setError]=useState('');const [sending,setSending]=useState(false);const [uploading,setUploading]=useState(false);const [uploadRole,setUploadRole]=useState('auto');const [uploadResults,setUploadResults]=useState<{name:string;ok:boolean;message:string}[]>([]);
 const draftKey=projectId+':'+(chatId||'new');const {content,target,asRequirement,setContent,setTarget,setAsRequirement,move:moveDraft,clearSubmitted,version:draftVersion}=useDrafts(draftKey);const projectRef=useRef(projectId);projectRef.current=projectId;const nav=useRef(0);const creating=useRef<{project:string;token:number;promise:Promise<string>}|null>(null);const fileInput=useRef<HTMLInputElement>(null);const textarea=useRef<HTMLTextAreaElement>(null);const bottom=useRef<HTMLDivElement>(null);const chatRef=useRef(chatId);chatRef.current=chatId;
 const latestRun=snapshot?.runs?.slice().sort((a,b)=>b.updated_at.localeCompare(a.updated_at)).find(r=>busy(r));const running=busy(latestRun);const canInstruct=!!(running&&latestRun?.experience==='agent');const canEditPaused=!!(target&&latestRun?.status==='waiting'&&['scenario_review','strategy_review'].includes(latestRun.interrupt?.type??'')&&target.artifact.id===latestRun.interrupt?.artifact_id);const refreshKey=snapshot?.runs?.map(r=>r.id+':'+r.updated_at+':'+r.status).join('|')+':'+artifactEpoch;
 const refresh=useCallback(async()=>{if(!chatId)return;try{const state=await api<Snapshot>('/chats/'+chatId);if(chatRef.current===chatId)setSnapshot(state);}catch(e){if(chatRef.current===chatId)setError(errText(e));}},[chatId]);
 const reloadSettings=useCallback(async()=>{const [s,p]=await Promise.all([api<Settings>('/settings'),projectId?api<Profile[]>('/projects/'+projectId+'/profiles'):Promise.resolve([])]);setSettings(s);if(projectRef.current===projectId){setProfiles(p);setProfileId(old=>p.some(x=>x.id===old)?old:p[0]?.id??'');}},[projectId]);
 useEffect(()=>{api<Project[]>('/projects').then(list=>{setProjects(list);setProjectId(list[0]?.id??'');}).catch(e=>setError(errText(e)));api<Settings>('/settings').then(setSettings).catch(e=>setError(errText(e)));},[]);
 useEffect(()=>{if(!projectId)return;let active=true;setProjectLoading(true);setSnapshot(undefined);setChatId('');chatRef.current='';setChats([]);setProfiles([]);setProfileId('');Promise.all([api<Chat[]>('/projects/'+projectId+'/chats'),api<Profile[]>('/projects/'+projectId+'/profiles')]).then(([c,p])=>{if(active){setChats(c);setProfiles(p);setProfileId(p[0]?.id??'');setChatId(c[0]?.id??'');chatRef.current=c[0]?.id??'';}}).catch(e=>active&&setError(errText(e))).finally(()=>{if(active)setProjectLoading(false);});return()=>{active=false;};},[projectId]);
 useEffect(()=>{setSnapshot(undefined);setError('');refresh();},[refresh]);
 useEffect(()=>{if(!chatId)return;const timer=setInterval(refresh,7000);return()=>clearInterval(timer);},[chatId,running,refresh]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth',block:'end'});},[chatId,snapshot?.messages.length,latestRun?.interrupt?.type]);
 function selectProject(id:string){setOpenedArtifact(undefined);setProjectLoading(true);nav.current++;projectRef.current=id;chatRef.current='';setProjectId(id);setChatId('');setChats([]);setProfiles([]);setSnapshot(undefined);setSettingsOpen(false);setSourcesOpen(false);}
 function selectChat(id:string){setOpenedArtifact(undefined);nav.current++;chatRef.current=id;setChatId(id);setSidebar(false);setSourcesOpen(false);}
 async function ensureChat(){
  if(projectLoading)throw new Error('正在加载项目，请稍候');
  if(chatRef.current)return chatRef.current;
  const pid=projectRef.current;const token=nav.current;
  if(!pid)throw new Error('项目尚未加载，请稍后重试');
  if(creating.current?.project===pid&&creating.current.token===token)return creating.current.promise;
  const promise=api<Chat>('/projects/'+pid+'/chats',{}).then(chat=>{if(projectRef.current===pid&&nav.current===token){setChats(old=>[chat,...old]);moveDraft(pid+':new',pid+':'+chat.id);chatRef.current=chat.id;setChatId(chat.id);}return chat.id;});
  creating.current={project:pid,token,promise};
  try{return await promise;}finally{if(creating.current?.promise===promise)creating.current=null;}
 }
 async function newChat(){
  if(projectLoading)return;
  const pid=projectRef.current;const token=++nav.current;setError('');setOpenedArtifact(undefined);
  try{const chat=await api<Chat>('/projects/'+pid+'/chats',{});if(projectRef.current!==pid||nav.current!==token)return;setChats(old=>[chat,...old]);chatRef.current=chat.id;setChatId(chat.id);setSidebar(false);textarea.current?.focus();}catch(e){if(nav.current===token)setError(errText(e));}
 }
 async function send(generationMessage?:string){
  if(!(generationMessage??content).trim()||projectLoading||sending||uploading||(running&&!canEditPaused&&!canInstruct))return;
  if(canInstruct&&target){setError('请在当前任务完成后修改已有结果。可以取消修改目标后，补充本轮要求。');return;}
  const pid=projectRef.current;const token=nav.current;const message=generationMessage??content;const submittedVersion=draftVersion;const submittedTarget=generationMessage?undefined:target;
  setMobilePanel('chat');
  setSending(true);setError('');
  try{
   const id=await ensureChat();
   if(canInstruct&&latestRun)await api('/runs/'+latestRun.id+'/instructions',{content:message});
   else if(canEditPaused&&latestRun)await api('/runs/'+latestRun.id+'/edit',{content:message,...(submittedTarget?.ids.length?{selected_ids:submittedTarget.ids}:{})});
   else await api('/chats/'+id+'/messages',{content:message,experience:'reliable',depth,...(caseTypesTouched?{case_types:caseTypes}:{}),profile_override:runOverride,as_requirement:asRequirement||(!snapshot?.sources.length&&!submittedTarget&&['auto','generate_case','review_requirement','generate_scenario'].includes(intent)),intent:submittedTarget?'modify':generationMessage?intent==='auto'?'generate_case':intent:intent,mode,profile_id:profileId||undefined,...(submittedTarget?{artifact_id:submittedTarget.artifact.id,...(submittedTarget.ids.length?{selected_ids:submittedTarget.ids}:{})}:{})});
   setRunOverride(undefined);clearSubmitted(pid+':'+id,submittedVersion);
   const [state,list]=await Promise.all([api<Snapshot>('/chats/'+id),api<Chat[]>('/projects/'+pid+'/chats')]);
   if(chatRef.current===id&&projectRef.current===pid)setSnapshot(state);
   if(projectRef.current===pid)setChats(list);
  }catch(e){if(nav.current===token)setError(errText(e));}finally{setSending(false);}
 }
 async function upload(files:FileList|null){
  if(!files?.length||uploading)return;const token=nav.current;setUploading(true);setError('');
  try{const id=await ensureChat();const results=[];for(const file of Array.from(files)){const form=new FormData();form.append('file',file);form.append('role',uploadRole);try{await api('/chats/'+id+'/sources',form);results.push({name:file.name,ok:true,message:'上传成功'});}catch(e){results.push({name:file.name,ok:false,message:errText(e)});}}setUploadResults(results);const state=await api<Snapshot>('/chats/'+id);if(chatRef.current===id)setSnapshot(state);}catch(e){if(nav.current===token)setError(errText(e));}finally{setUploading(false);if(fileInput.current)fileInput.current.value='';}
 }
 useEffect(()=>{if(target)textarea.current?.focus();},[target]);
 function selectTarget(artifact:Artifact,ids:string[]){setMobilePanel('chat');if(running&&!(latestRun?.status==='waiting'&&['scenario_review','strategy_review'].includes(latestRun.interrupt?.type??'')&&artifact.id===latestRun.interrupt?.artifact_id)){setError('请在当前任务完成后修改已有结果。本轮补充要求可直接在聊天中发送。');return;}setTarget({artifact,ids});textarea.current?.focus();}
 const lastAssistantForRun=new Map(snapshot?.messages.filter(m=>m.role==='assistant'&&m.metadata?.run_id).map(m=>[m.metadata.run_id,m.id]));
 const latestOutput=snapshot?.messages.flatMap(m=>m.metadata?.artifact_ids??[]).at(-1) as string|undefined;
 const draftOutput=snapshot?.runs.filter(r=>r.status!=='completed'&&r.draft_artifact_id).at(-1)?.draft_artifact_id;
 const visibleOutput=draftOutput??latestOutput;
 useEffect(()=>{let alive=true;if(!visibleOutput){setOpenedArtifact(undefined);return;}api<Artifact>('/artifacts/'+visibleOutput).then(a=>{if(alive)setOpenedArtifact(a);}).catch(()=>{});return()=>{alive=false;};},[visibleOutput,chatId]);
 const completedRuns=new Set(snapshot?.runs.filter(r=>r.status==='completed').map(r=>r.id));
 const openSettings=(value?:Json,tab:'model'|'profile'='model')=>{setProposal(value);setSettingsTab(tab);setSettingsOpen(true);};
 const openResult=(a:Artifact)=>{setOpenedArtifact(a);setWorkspaceOpen(true);setMobilePanel('results');};
 return <div className={'app-shell v24 panel-'+mobilePanel+(snapshot?.messages.length?' has-messages':' intake-page')+(workspaceOpen&&openedArtifact?' workspace-open':'')} style={{'--result-width':workspaceWidth+'%'} as CSSProperties}>
  <div className="mobile-panel-switch"><button className={mobilePanel==='results'?'active':''} onClick={()=>{setMobilePanel('results');setWorkspaceOpen(true);}}>结果工作区</button><button className={mobilePanel==='chat'?'active':''} onClick={()=>setMobilePanel('chat')}>AI 助手</button><button onClick={()=>setSidebar(true)} aria-label="项目导航"><Menu size={18}/></button></div>
  {sidebar&&<button className="sidebar-backdrop" aria-label="收起对话列表" onClick={()=>setSidebar(false)}/>}
  <aside className={'sidebar '+(sidebar?'open':'')}><div className="brand"><Logo/><span>TCG <small>TEST WORKSPACE</small></span><button className="icon-button mobile-only" aria-label="收起侧栏" onClick={()=>setSidebar(false)}><X size={20}/></button></div><button className="primary new-chat" disabled={!projectId||projectLoading} onClick={newChat}><Plus size={20}/>新建生成会话</button><div className="project-select"><Folder size={18}/><select aria-label="当前项目" value={projectId} onChange={e=>selectProject(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="icon-button" aria-label="创建项目" onClick={()=>setProjectDialog(true)}><Plus size={15}/></button></div><div className="nav-section"><button className="nav-current" onClick={()=>setMobilePanel('results')}><FileText size={17}/>用例生成</button><button onClick={async()=>{try{await ensureChat();setSourcesOpen(true);}catch(e){setError(errText(e));}}}><Folder size={17}/>需求资料</button><button onClick={()=>setMemoryOpen(true)}><MessageSquare size={17}/>项目记忆</button></div><p className="sidebar-label">生成会话</p><nav className="chat-list" aria-label="对话历史">{chats.map(chat=><button key={chat.id} className={chat.id===chatId?'active':''} onClick={()=>selectChat(chat.id)}><MessageSquare size={17}/><span>{chat.title}</span></button>)}{!chats.length&&<p className="muted small-text sidebar-empty">开始一次对话，需求和结果会保留在这里。</p>}</nav><button className="settings-button" onClick={()=>openSettings()}><SettingsIcon size={20}/>模型与设置<span className={'connection-dot '+(settings?.model?'ready':'')}/></button></aside>
  <main className="main"><header className="topbar"><div className="inline"><button className="icon-button mobile-only" aria-label="打开对话列表" onClick={()=>setSidebar(true)}><Menu size={22}/></button><h1>生成测试用例</h1></div><div className="topbar-actions"><button onClick={()=>openSettings(undefined,'profile')}>Profile 与 Excel 模板</button><button className="text-accent" disabled={projectLoading} onClick={()=>setMemoryOpen(true)}>项目记忆</button><button className="text-accent" disabled={projectLoading} onClick={async()=>{try{await ensureChat();setSourcesOpen(true);}catch(e){setError(errText(e));}}}><Link size={17}/>需求来源{snapshot?.sources.length?` · ${snapshot.sources.length}`:''}</button></div></header>
  <div className="session-context"><span>AI AUTHORING</span><label>Profile<select aria-label="运行 Profile" value={profileId} disabled={running} onChange={e=>setProfileId(e.target.value)}>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{runOverride&&<span>本轮使用临时配置 <button onClick={()=>setRunOverride(undefined)}>取消</button></span>}{openedArtifact&&<button onClick={()=>{setWorkspaceOpen(!workspaceOpen);setMobilePanel('results');}}>{workspaceOpen?'收起结果面板':'并排查看结果'}</button>}</div>
  <div className="conversation" id="conversation"><div className="conversation-inner">
   {!snapshot?.messages.length?<div className="welcome"><Logo/><h2>你想测试什么？</h2><p>描述功能、粘贴需求，或上传一份文档。<br/>一起理解业务、确认场景，再生成可追溯的测试用例。</p><div className="starter-actions"><button onClick={()=>{setIntent('generate_case');textarea.current?.focus();}}><FileText size={18}/>生成测试用例</button><button onClick={()=>{setIntent('review_requirement');textarea.current?.focus();}}><MessageSquare size={18}/>一起梳理需求</button></div>{!settings?.model&&<button className="setup-link" onClick={()=>openSettings()}>首次使用，先连接一个模型 <ArrowUp size={15} className="arrow-right"/></button>}</div>:snapshot.messages.map(message=><article className={'message '+message.role} key={message.id}>{message.role==='assistant'&&<Logo small/>}<div className="message-body"><div className="message-text preserve">{message.content}</div>{message.metadata?.artifact_ids?.map((id:string)=><ArtifactCard key={id} id={id} onOpen={openResult} refreshKey={refreshKey} onTarget={selectTarget} onChanged={()=>{setArtifactEpoch(x=>x+1);refresh();}}/>)}{message.metadata?.refs?.length>0&&<p className="muted small-text">依据：{message.metadata.refs.join(' · ')}</p>}{message.metadata?.proposal&&<button className="primary" onClick={()=>openSettings(message.metadata.proposal.config??message.metadata.proposal)}>查看并应用 Profile 建议</button>}{message.role==='assistant'&&completedRuns.has(message.metadata?.run_id)&&lastAssistantForRun.get(message.metadata.run_id)===message.id&&<RunTimeline runId={message.metadata.run_id} initialOpen={false} agentLive={false} agentMode={snapshot.runs.find(r=>r.id===message.metadata.run_id)?.experience==='agent'} initialAgent={snapshot.runs.find(r=>r.id===message.metadata.run_id)?.agent}/>} {message.role==='assistant'&&message.metadata?.run_id&&<a className="run-log-link text-accent" href={'/api/runs/'+encodeURIComponent(message.metadata.run_id)+'/diagnostics?download=true'} download>下载本轮诊断日志</a>}</div></article>)}
   {snapshot?.runs.filter(run=>run.status!=='completed').map(run=><div className="message assistant" key={run.id}><Logo small/><div className="message-body"><RunCard run={run} onChanged={()=>{setArtifactEpoch(x=>x+1);refresh();}} onTarget={selectTarget} onSettings={()=>openSettings()}/></div></div>)}<div ref={bottom}/>
  </div></div>
  <div className="composer-wrap"><div className="composer-inner"><ErrorBox message={error}/>{target&&<div className="target-bar"><span>修改：{target.artifact.title}{target.ids.length?` · 选中 ${target.ids.length} 条`:' · 全部条目'}</span><button className="icon-button" aria-label="取消修改目标" onClick={()=>setTarget(undefined)}><X size={15}/></button></div>}
   {snapshot?.sources.length?<div className="attachment-list">{snapshot.sources.map(source=><button key={source.id} className="attachment-chip" onClick={()=>setSourcesOpen(true)}><FileText size={15}/><span>{source.name}</span><small>{roles[source.role]??source.role}</small></button>)}</div>:null}{uploadResults.length>0&&<div className="upload-results" aria-label="上传结果">{uploadResults.map((result,index)=><span className={result.ok?'success':'error-text'} key={result.name+index}>{result.name}：{result.message}</span>)}</div>}
   <div className="composer"><div className="composer-input"><textarea ref={textarea} aria-label="聊天输入" rows={2} placeholder={canInstruct?'可以补充要求，我会调整当前任务…':(target||openedArtifact)?'告诉我如何修改这些用例…':'描述你想测试的内容，或上传需求文档…'} value={content} onChange={e=>setContent(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}}/><button className="send-button" aria-label="发送消息" disabled={!content.trim()||projectLoading||sending||(running&&!canEditPaused&&!canInstruct)||uploading} onClick={()=>send()}>{sending?<Spinner/>:<ArrowUp size={23}/>}</button></div><div className="composer-tools"><div className="tool-group"><input ref={fileInput} type="file" multiple accept=".docx,.pdf,.xlsx,.xls,.csv,.txt,.md" hidden onChange={e=>upload(e.target.files)}/><button className="icon-button attachment-button" disabled={projectLoading||uploading||running} title="上传需求文档" aria-label="上传需求文档" onClick={()=>fileInput.current?.click()}>{uploading?<Spinner/>:<Paperclip size={21}/>}</button><label className="visible-mode">MODE<select aria-label="运行模式" value={mode} disabled={running} onChange={e=>setMode(e.target.value as 'auto'|'hitp')}><option value="auto">Auto · 自动完成</option><option value="hitp">HITP · 人工关键节点</option></select></label><button className="task-options-toggle" aria-expanded={optionsOpen} onClick={()=>setOptionsOpen(value=>!value)}>本次方案 · {depthNames[depth]}<ChevronDown size={14}/></button>{canInstruct&&<span className="composer-live">可随时补充要求</span>}</div></div>
   {optionsOpen&&<div className="task-options"><label>测试设计深度<select value={depth} onChange={e=>setDepth(e.target.value as Depth)}>{(['auto','quick','standard','deep'] as Depth[]).map(value=><option key={value} value={value}>{depthNames[value]}</option>)}</select></label><p className="option-description">{depth==='quick'?'聚焦核心路径与重要风险，列明未展开的范围。':depth==='deep'?'深入状态变化、条件组合和跨模块风险。':'覆盖日常需求的业务规则、异常和边界。'}</p><fieldset className="case-type-options"><legend>用例类型</legend>{['Business','Negative','Boundary','Security'].map(value=><label className="check-label" key={value}><input type="checkbox" aria-label={value} checked={caseTypes.includes(value)} onChange={e=>{setCaseTypesTouched(true);setCaseTypes(old=>e.target.checked?[...old,value]:old.filter(x=>x!==value));}}/>{value}</label>)}</fieldset><fieldset className="mode-options"><legend>执行方式</legend><label className="check-label"><input type="radio" name="run-mode" checked={mode==='auto'} onChange={()=>setMode('auto')}/>自动执行</label><label className="check-label"><input type="radio" name="run-mode" aria-label="人工确认关键节点" checked={mode==='hitp'} onChange={()=>setMode('hitp')}/>人工确认关键节点</label></fieldset><details><summary>指定任务与资料用途</summary><div className="advanced-task-options"><label>任务目标<select aria-label="任务目标" disabled={!!target} value={intent} onChange={e=>setIntent(e.target.value)}>{intents.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>上传文件角色<select aria-label="上传文件角色" value={uploadRole} onChange={e=>setUploadRole(e.target.value)}>{Object.entries(roles).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="check-label"><input type="checkbox" aria-label="这条消息是需求正文" checked={asRequirement} onChange={e=>setAsRequirement(e.target.checked)}/>将这条消息保存为需求正文</label></div></details></div>}
   </div><div className="intent-shortcuts"><span>选择任务</span>{intents.map(([value,label])=><button key={value} disabled={running||!!target} className={intent===value?'active':''} onClick={()=>{setIntent(value);if(value==='learn_template'){setUploadRole('example');}textarea.current?.focus();}}>{label}</button>)}<button disabled={running} onClick={()=>openSettings(undefined,'profile')}>编辑 Profile / Excel 格式</button></div><p className="composer-note">{canInstruct?'补充内容会在安全的步骤边界应用，已有结果会保留。':running?'任务执行中，停止或完成后可发送下一条消息。':'Enter 发送 · Shift + Enter 换行'}<span>结果可追溯至需求原文，请结合业务复核。</span></p>
  </div></div></main>
  {workspaceOpen&&openedArtifact&&<div className="result-dock"><div className="dock-tools"><label>面板宽度<input aria-label="结果面板宽度" type="range" min={25} max={55} value={workspaceWidth} onChange={e=>setWorkspaceWidth(Number(e.target.value))}/></label><button aria-label="关闭结果面板" onClick={()=>{setWorkspaceOpen(false);setMobilePanel('chat');}}><X size={18}/></button></div><ArtifactWorkspace artifact={openedArtifact} refreshKey={refreshKey} onTarget={selectTarget} onChanged={()=>{setArtifactEpoch(x=>x+1);refresh();}} sourceCount={snapshot?.sources.length??0} running={running||sending||uploading||projectLoading} onUpload={()=>fileInput.current?.click()} onGenerate={()=>send('请继续生成测试用例。')}/></div>}

  {settingsOpen&&<SettingsDialog initialTab={settingsTab} onUseOnce={setRunOverride} projectId={projectId} profiles={profiles} activeProfileId={profileId} onSelectProfile={setProfileId} proposal={proposal} onClose={()=>setSettingsOpen(false)} onSaved={()=>reloadSettings().catch(e=>setError(errText(e)))}/>}
  {sourcesOpen&&chatId&&<SourcesDialog chatId={chatId} sources={snapshot?.sources??[]} onChanged={()=>{setArtifactEpoch(x=>x+1);refresh();}} onClose={()=>setSourcesOpen(false)}/>}
  {memoryOpen&&projectId&&<MemoryDialog projectId={projectId} onClose={()=>setMemoryOpen(false)}/>}
  {projectDialog&&<Dialog title="创建项目" onClose={()=>setProjectDialog(false)}><label>项目名称<input autoFocus value={projectName} onChange={e=>setProjectName(e.target.value)} placeholder="例如：订单服务"/></label><div className="dialog-actions"><button className="primary" disabled={!projectName.trim()} onClick={async()=>{try{const p=await api<Project>('/projects',{name:projectName.trim()});setProjects(old=>[...old,p]);selectProject(p.id);setProjectDialog(false);setProjectName('');}catch(e){setError(errText(e));}}}>创建项目</button></div></Dialog>}
 </div>;
}
