import {useEffect,useMemo,useRef,useState} from 'react';
import {Check,ChevronDown,ChevronUp,Download,FileText,History,MessageSquare,PenLine,Plus,Trash2} from 'lucide-react';
import {AnalysisReport} from './AnalysisReport';
import {TemplateUsage} from './TemplateUsage';
import {ArtifactActions} from './ArtifactActions';
import {ArtifactLineage,ArtifactScope,CaseReview,RowStatus,matchesScope,rowContext,useArtifactLineage} from './ArtifactLineage';
import type {RowContext,ScopeFilter} from './ArtifactLineage';
import {PinSamples} from './ProjectSamples';
import {canEditItems,ItemEditor} from './ItemEditor';
import {api,downloadArtifact,errText} from './api';
import {Dialog,ErrorBox,Spinner,TextValue} from './ui';
import type {Artifact,Json,Source} from './types';

export function ArtifactCard({chatOnly=false,id,refreshKey,onTarget,onChanged,compact=false,onOpen,initialDetailsOpen=false,initialSelectedIds=[],snapshot,revision,readOnly=false,simplified=false,reviewMode=false,onEditingChange,onSelectionChange}:{chatOnly?:boolean;initialSelectedIds?:string[];onSelectionChange?:(artifact:Artifact,selected:string[],viewOrder:string[])=>void;onEditingChange?:(editing:boolean)=>void;reviewMode?:boolean;simplified?:boolean;snapshot?:Artifact;revision?:number;readOnly?:boolean;id:string;refreshKey?:string;onTarget:(artifact:Artifact,selected:string[],viewOrder?:string[])=>void;onChanged:()=>void;compact?:boolean;onOpen?:(artifact:Artifact)=>void;initialDetailsOpen?:boolean}){
 const selectionCallback=useRef(onSelectionChange);selectionCallback.current=onSelectionChange;
 const [data,setData]=useState<Artifact|undefined>(snapshot);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 const lineage=useArtifactLineage(data,!compact&&['analysis','scenarios','cases'].includes(data?.type??''));
 const [rowFilter,setRowFilter]=useState<ScopeFilter>('all');const [typeFilter,setTypeFilter]=useState('');const [priorityFilter,setPriorityFilter]=useState('');const [visibleColumns,setVisibleColumns]=useState<string[]>([]);
 const [selected,setSelected]=useState<string[]>(initialSelectedIds);const [expanded,setExpanded]=useState<string>();
 const [expandAll,setExpandAll]=useState<boolean|undefined>();const [scenarioSaved,setScenarioSaved]=useState(false);const [syncRequest,setSyncRequest]=useState(0);
 useEffect(()=>{setExpandAll(undefined);setExpanded(undefined);setScenarioSaved(false);setRowFilter('all');setTypeFilter('');setPriorityFilter('');setVisibleColumns([]);setSelected(initialSelectedIds);},[id]);
 useEffect(()=>{setExpandAll(undefined);setExpanded(undefined);},[initialDetailsOpen]);
 const [reportDraft,setReportDraft]=useState<Json>({});
 const [editor,setEditor]=useState(false);const [baseRevision,setBaseRevision]=useState(0);const [editorMode,setEditorMode]=useState('form');const [draft,setDraft]=useState('');const [history,setHistory]=useState<Json[]|null>(null);
 useEffect(()=>{onEditingChange?.(editor);return()=>onEditingChange?.(false);},[editor,onEditingChange]);
 const [historyItem,setHistoryItem]=useState<Artifact>();const [exporting,setExporting]=useState(false);
 const [exportOptions,setExportOptions]=useState<Json>();const [exportProfile,setExportProfile]=useState('');const exportChoiceTouched=useRef(false);const exportSelectedProfile=useRef('');
 useEffect(()=>{if(!exporting||!data)return;let active=true;setExportOptions(undefined);api('/artifacts/'+id+'/export-options?revision='+data.revision).then(v=>{if(active){setExportOptions(v);const selectedProfile=exportChoiceTouched.current?exportSelectedProfile.current:(v.default_profile_id??'');exportSelectedProfile.current=selectedProfile;setExportProfile(selectedProfile);const chosen=v.profiles?.find((p:Json)=>p.id===selectedProfile);setLayout(chosen?.config.excel_layout??v.snapshot.excel_layout??'case');}}).catch(e=>active&&setError(errText(e)));return()=>{active=false;};},[exporting,id,data?.revision,refreshKey]);
 const [layout,setLayout]=useState('case');const [scope,setScope]=useState('all');const [evidence,setEvidence]=useState<{ref:string;source:Source}[]|null>(null);
 useEffect(()=>{let alive=true;if(snapshot){setData(snapshot);return;}const request=revision===undefined?api<Artifact>('/artifacts/'+id):Promise.all([api<Artifact>('/artifacts/'+id),api<Artifact>('/artifacts/'+id+'/revisions/'+revision)]).then(([latest,saved])=>({...latest,...saved,id,revision}));request.then(value=>{if(alive){setData(value);setSelected(old=>old.filter(item=>value.items.some(x=>x.id===item)));setError('');}}).catch(e=>alive&&setError(errText(e)));return()=>{alive=false;};},[id,revision,revision===undefined?refreshKey:undefined,snapshot]);
 async function save(){if(!data)return;setError('');setLoading(true);try{const items=JSON.parse(draft);if(!Array.isArray(items))throw new Error('内容必须是 JSON 数组');setData(await api('/artifacts/'+id,{expected_revision:baseRevision,items,...(data.type==='analysis'?{report:reportDraft}:{})},'PUT'));setEditor(false);if(data.type==='scenarios')setScenarioSaved(true);onChanged();}catch(e){setError(errText(e));}finally{setLoading(false);}}
 async function showEvidence(refs:string[]){setLoading(true);setError('');try{const ids=[...new Set(refs.map(ref=>ref.split('#')[0]))];const sources=await Promise.all(ids.map(sourceId=>api<Source>('/sources/'+encodeURIComponent(sourceId))));setEvidence(refs.map(ref=>({ref,source:sources.find(s=>s.id===ref.split('#')[0])!})));}catch(e){setError(errText(e));}finally{setLoading(false);}}
 async function showHistory(){setError('');try{setHistory(await api('/artifacts/'+id+'/revisions'));setHistoryItem(undefined);}catch(e){setError(errText(e));}}
 async function restore(){if(!historyItem||!data)return;setLoading(true);try{setData(await api('/artifacts/'+id+'/restore',{revision:historyItem.revision,expected_revision:data.revision}));setHistory(null);onChanged();}catch(e){setError(errText(e));}finally{setLoading(false);}}
 const caseExport=data?.type==='cases';
 const exportCheck=caseExport?(exportProfile?exportOptions?.profiles?.find((p:Json)=>p.id===exportProfile)?.field_check:exportOptions?.snapshot_check):undefined;
 const exportIds=scope==='selected'?selected:data?.view_item_ids;
 const missingFields=(exportCheck?.missing??[]).filter((gap:Json)=>exportIds===undefined||exportIds.includes(gap.id));
 async function completeFields(){if(!data)return;setLoading(true);setError('');try{await api('/artifacts/'+id+'/complete-fields',{expected_revision:data.revision,...(exportProfile?{profile_id:exportProfile}:{}),...(scope==='selected'?{selected_ids:selected}:{})});setExporting(false);onChanged();}catch(e){setError(errText(e));}finally{setLoading(false);}}
 function editMissingFields(){if(!data)return;setDraft(JSON.stringify(data.items,null,2));setBaseRevision(data.revision);setEditorMode('form');setExporting(false);setEditor(true);}
 const allDetailsOpen=expandAll??(initialDetailsOpen||(!simplified&&!!data?.report?.review_reports?.length));
 const contexts=useMemo(()=>new Map((data?.items??[]).map(item=>[item.id,rowContext(data!,item,lineage.workspace)])),[data,lineage.workspace]);
 const filteredItems=(data?.items??[]).filter(item=>matchesScope(contexts.get(item.id)!,rowFilter,data!.type)&&(!typeFilter||item.type===typeFilter)&&(!priorityFilter||item.priority===priorityFilter));
 const viewOrder=filteredItems.map(item=>String(item.id));const viewOrderKey=JSON.stringify(viewOrder);
 useEffect(()=>{if(data&&!readOnly&&!compact)selectionCallback.current?.(data,selected,viewOrder);},[data,selected,viewOrderKey,readOnly,compact]);
 const customColumns:Json[]=(data?.report?.template_usage?.field_contract??data?.report?.template_usage?.columns??[]).filter((column:Json,index:number,all:Json[])=>typeof column.field==='string'&&!['id','title','type','priority','preconditions','scenario_id','steps','expected','refs'].includes(column.field)&&!column.field.startsWith('_')&&all.findIndex(c=>c.field===column.field)===index);
 const shownColumns=customColumns.filter(column=>visibleColumns.includes(column.field));
 const allRefs=[...new Set(data?.items.flatMap(item=>item.refs??[])??[])] as string[];
 if(!data)return <div className="artifact"><ErrorBox message={error}/>{!error&&<p className="muted inline"><Spinner/> 正在读取产物…</p>}</div>;
 if(data.type==='answer')return null;
 if(compact)return <button className="artifact-preview" aria-label={'打开成果 · '+data.title+' · v'+data.revision} onClick={()=>onOpen?.(data)}><span className="artifact-preview-icon"><FileText size={22}/></span><span><strong>{data.title}</strong><small>{data.items.length} 条 · v{data.revision} · {readOnly?'查看此版本':'查看详情、编辑和导出'}</small></span><ChevronDown size={17} className="artifact-preview-arrow"/></button>;
 return <section className="artifact" aria-label={data.title}>
  <div className="artifact-head"><div><h3>{data.title}</h3><span className="muted small-text">{data.items.length} 条 · v{data.revision}</span></div><div className="actions">{readOnly&&onOpen&&<button onClick={async()=>{try{onOpen(await api<Artifact>('/artifacts/'+id));}catch(e){setError(errText(e));}}}>打开最新版本</button>}{!chatOnly&&!readOnly&&<button onClick={()=>{setReportDraft(data.report??{});setDraft(JSON.stringify(data.items,null,2));setBaseRevision(data.revision);setEditorMode(canEditItems(data.items,data.type)?'form':'json');setEditor(true);setError('');}}><PenLine size={16}/>编辑</button>}{!simplified&&<button onClick={showHistory}><History size={16}/>历史版本</button>}{['cases','scenarios'].includes(data.type)&&<button className="text-accent" onClick={()=>{setError('');setScope(selected.length?'selected':'all');exportChoiceTouched.current=false;exportSelectedProfile.current='';setExportProfile('');setExporting(true);}}><Download size={16}/>导出 Excel</button>}</div></div>
  <ErrorBox message={error}/>
  {!simplified&&data.report?.template_usage&&<TemplateUsage usage={data.report.template_usage}/>}
  {!chatOnly&&!readOnly&&!simplified&&<ArtifactActions artifact={data} selected={selected} onChanged={onChanged} syncRequest={syncRequest} onSaved={artifacts=>{const current=artifacts.find(item=>item.id===id);if(current){setData(current);if(current.type==='scenarios')setScenarioSaved(true);}}}/>}
  {!chatOnly&&!readOnly&&!simplified&&data.type==='cases'&&<PinSamples artifact={data} selectedIds={selected} onChanged={onChanged}/>}
  {!chatOnly&&!simplified&&scenarioSaved&&data.type==='scenarios'&&<div className="scenario-saved-actions"><span>场景新版本已保存，可查看并预览关联用例的调整。</span><button onClick={()=>setSyncRequest(x=>x+1)}>查看影响 / 同步关联用例</button><button className="icon-button" aria-label="收起场景保存提示" onClick={()=>setScenarioSaved(false)}>×</button></div>}
  {lineage.workspace&&['analysis','scenarios','cases'].includes(data.type)&&<ArtifactScope artifact={data} workspace={lineage.workspace} filter={rowFilter} onFilter={setRowFilter} contexts={contexts}/>}
  {lineage.error&&<p className="muted small-text" role="status">关联暂不可读取：{lineage.error}</p>}
  {['cases','scenarios'].includes(data.type)&&<div className="artifact-table-tools artifact-row-tools"><div className="actions"><label>类型<select aria-label="筛选类型" value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="">全部</option>{[...new Set(data.items.map(item=>item.type).filter(Boolean))].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label>优先级<select aria-label="筛选优先级" value={priorityFilter} onChange={e=>setPriorityFilter(e.target.value)}><option value="">全部</option>{[...new Set(data.items.map(item=>item.priority).filter(Boolean))].map(value=><option key={value} value={value}>{value}</option>)}</select></label>{!readOnly&&selected.length>0&&<span className="muted small-text">已选择 {selected.length} 条{selected.some(id=>!filteredItems.some(item=>item.id===id))?'（含筛选外条目）':''}</span>}</div><div className="actions">{customColumns.length>0&&<details className="artifact-column-picker"><summary>显示模板列</summary>{customColumns.map(column=><label key={column.field}><input type="checkbox" aria-label={'显示 '+column.header} checked={visibleColumns.includes(column.field)} onChange={e=>setVisibleColumns(old=>e.target.checked?[...old,column.field]:old.filter(field=>field!==column.field))}/>{column.header}</label>)}</details>}{data.type==='cases'&&<button onClick={()=>{setExpandAll(!allDetailsOpen);setExpanded(undefined);}}>{allDetailsOpen?'收起全部步骤':'展开全部步骤'}</button>}</div></div>}
  {['cases','scenarios'].includes(data.type)?<div className="table-scroll artifact-inline-table"><table data-read-only={readOnly} aria-label={data.type==='cases'?'用例与评审':'场景与需求'}><thead><tr>{!readOnly&&<th className="select-col"><input type="checkbox" aria-label="选择全部条目" checked={!!filteredItems.length&&filteredItems.every(item=>selected.includes(item.id))} onChange={e=>setSelected(old=>e.target.checked?[...new Set([...old,...filteredItems.map(item=>item.id)])]:old.filter(id=>!filteredItems.some(item=>item.id===id)))}/></th>}<th>编号</th><th>标题</th><th>类型</th><th>优先级</th>{data.type==='cases'&&<><th>前置条件</th><th>操作 / Step</th><th>预期结果 / Expected result</th></>}<th>{data.type==='cases'?'主场景 / 对应需求':'对应需求 / 关联用例'}</th>{data.type==='cases'&&<th>评审意见</th>}{shownColumns.map(column=><th key={column.field}>{column.header}</th>)}<th aria-label="展开"/></tr></thead><tbody>{filteredItems.map(item=><ArtifactRow key={item.id} item={item} kind={data.type} readOnly={readOnly} context={contexts.get(item.id)!} lineageLoading={!lineage.workspace} lineageError={lineage.error} columns={shownColumns} hasReview={!!data.report?.review_reports?.length} checked={selected.includes(item.id)} expanded={allDetailsOpen||expanded===item.id} onCheck={()=>setSelected(old=>old.includes(item.id)?old.filter(x=>x!==item.id):[...old,item.id])} onExpand={()=>{if(allDetailsOpen){setExpandAll(false);setExpanded(undefined);}else setExpanded(expanded===item.id?undefined:item.id);}} onEvidence={()=>showEvidence(item.refs??[])}/>)}</tbody></table>{!filteredItems.length&&<p className="muted artifact-filter-empty">当前筛选没有条目。<button onClick={()=>{setRowFilter('all');setTypeFilter('');setPriorityFilter('');}}>显示全部</button></p>}</div>:<div className="artifact-content">{filteredItems.map((item,index)=><div key={item.id??index} className="analysis-item"><strong>{item.id&&<span className="artifact-parent-id">{item.id} · </span>}{item.title??item.id??'结果'}</strong><p><TextValue value={item.description??item.answer??item.content??item}/></p>{data.type==='analysis'&&lineage.workspace&&<div className="artifact-analysis-links"><span className="muted small-text">{contexts.get(item.id)!.downstream.length?`关联场景：${contexts.get(item.id)!.downstream.join('、')}`:contexts.get(item.id)!.excluded?'本轮已排除':'尚无关联场景'}</span><RowStatus context={contexts.get(item.id)!}/></div>}{item.refs?.length>0&&<button className="text-accent" onClick={()=>showEvidence(item.refs)}><FileText size={14}/>需求依据 · {item.refs.length}</button>}</div>)}</div>}
  {data.report&&Object.keys(data.report).length>0&&<details className="coverage-details" open={reviewMode||undefined}><summary>{reviewMode?'评审意见与说明':'需求理解、覆盖说明与待确认项'}{data.report.unresolved_rows?.length?` · ${data.report.unresolved_rows.length} 条待修复`:""}</summary><AnalysisReport report={['cases','scenarios'].includes(data.type)?{...data.report,traceability:undefined}:data.report}/></details>}
  <div className="artifact-foot">{!simplified&&<button className="text-accent" disabled={!allRefs.length||loading} onClick={()=>showEvidence(allRefs)}><FileText size={16}/>查看需求依据</button>}{!chatOnly&&!readOnly&&<button disabled={!data.items.length||editor} onClick={()=>onTarget(data,selected,viewOrder)}><MessageSquare size={15}/>{selected.length?`让 AI 修改选中 ${selected.length} 条`:'让 AI 修改此结果'}</button>}</div>
  {simplified&&<details className="artifact-more-tools"><summary>更多工具与依据</summary><div className="actions"><button onClick={showHistory}><History size={16}/>历史版本</button><button disabled={!allRefs.length||loading} onClick={()=>showEvidence(allRefs)}><FileText size={16}/>查看需求依据</button></div>{!chatOnly&&!readOnly&&<><ArtifactActions centralized artifact={data} selected={selected} onChanged={onChanged} onSaved={artifacts=>{const current=artifacts.find(item=>item.id===id);if(current)setData(current);}}/>{data.type==='cases'&&<PinSamples artifact={data} selectedIds={selected} onChanged={onChanged}/>}</>}{data.report?.template_usage&&<TemplateUsage usage={data.report.template_usage}/>}</details>}
  {editor&&<Dialog title={'编辑 · '+data.title} onClose={()=>setEditor(false)} wide><p className="muted">修改标题、前置条件、操作或预期结果后，保存为新版本。未编辑的内容会保留。</p><div className="tabs"><button className={editorMode==='form'?'active':''} onClick={()=>{try{const value=JSON.parse(draft);if(!canEditItems(value,data.type))throw new Error();setEditorMode('form');setError('');}catch{setError('请先修正 JSON：每个条目必须是对象并包含 id，文本字段必须为字符串，refs 必须为字符串数组，用例 steps 必须是步骤对象数组。');}}}>表单编辑</button><button className={editorMode==='json'?'active':''} onClick={()=>setEditorMode('json')}>JSON · 全部字段</button></div>{editorMode==='json'?<textarea className="code-editor" aria-label="产物 JSON" value={draft} onChange={e=>setDraft(e.target.value)} spellCheck={false}/>:<ItemEditor items={JSON.parse(draft)} kind={data.type} columns={exportCheck?.columns??data.report?.template_usage?.field_contract??data.report?.template_usage?.columns} onChange={items=>setDraft(JSON.stringify(items,null,2))}/>}{data.type==='analysis'&&<div><label>需求理解摘要<textarea aria-label="需求理解摘要" value={reportDraft.summary??''} onChange={e=>setReportDraft({...reportDraft,summary:e.target.value})}/></label>{Array.isArray(reportDraft.diagrams)&&reportDraft.diagrams.map((d:Json,i:number)=><label key={i}>{d.title??'业务图'} · Mermaid<textarea aria-label={'图形源码 '+(i+1)} rows={6} value={d.mermaid??''} onChange={e=>setReportDraft({...reportDraft,diagrams:reportDraft.diagrams.map((x:Json,j:number)=>i===j?{...x,mermaid:e.target.value}:x)})}/></label>)}</div>}<p className="muted small-text">当前草稿基于 v{baseRevision}。</p><ErrorBox message={error}/>{error&&<button onClick={async()=>{try{const latest=await api<Artifact>('/artifacts/'+id);setData(latest);setDraft(JSON.stringify(latest.items,null,2));setBaseRevision(latest.revision);setError('');}catch(e){setError(errText(e));}}}>放弃草稿，载入最新版本</button>}<div className="dialog-actions"><button onClick={()=>{try{const items=JSON.parse(draft);items.push({id:'NEW-'+Date.now(),title:'新条目',refs:allRefs.slice(0,1),...(data.type==='cases'?{scenario_id:data.items[0]?.scenario_id??'',type:'Business',priority:'P2',preconditions:'',steps:[{action:'',expected:''}]}:{description:'',priority:'P2'})});setDraft(JSON.stringify(items,null,2));}catch{setError('请先修正 JSON 格式');}}}><Plus size={16}/>添加条目</button><button className="primary" disabled={loading} onClick={save}>{loading?<Spinner/>:<Check size={16}/>}保存新版本</button></div></Dialog>}
  {history&&<Dialog title="版本历史" onClose={()=>setHistory(null)} wide><div className="history-list">{history.map(item=><button key={item.revision} className={historyItem?.revision===item.revision?'selected':''} onClick={async()=>{try{setHistoryItem(await api('/artifacts/'+id+'/revisions/'+item.revision));}catch(e){setError(errText(e));}}}>v{item.revision}<span>{item.reason??'内容更新'}</span><small>{new Date(item.created_at).toLocaleString()}</small></button>)}</div>{historyItem&&<><pre className="json-preview">{JSON.stringify(historyItem.items,null,2)}</pre><details><summary>本次变更</summary><pre>{JSON.stringify(history.find(item=>item.revision===historyItem.revision)?.diff,null,2)}</pre></details><div className="dialog-actions"><span className="muted">恢复会创建新版本。</span>{!chatOnly&&!readOnly&&<button className="primary" disabled={loading||historyItem.revision===data.revision} onClick={restore}>恢复此版本</button>}</div></>}<ErrorBox message={error}/></Dialog>}
  {exporting&&<Dialog title={caseExport?'导出测试用例':'导出测试场景'} onClose={()=>setExporting(false)}><p className="muted small-text">导出正在查看的 v{data.revision}。</p><label>导出范围<select value={scope} onChange={e=>setScope(e.target.value)}><option value="all">{data.view_item_ids?'当前显示的':'全部'} {data.items.length} 条{caseExport?'用例':'场景'}</option><option value="selected" disabled={!selected.length}>选中 {selected.length} 条{caseExport?'用例':'场景'}</option></select></label><label>导出格式 Profile<select value={exportProfile} onChange={e=>{exportChoiceTouched.current=true;exportSelectedProfile.current=e.target.value;setExportProfile(e.target.value);const p=exportOptions?.profiles?.find((p:Json)=>p.id===e.target.value);setLayout(p?.config.excel_layout??exportOptions?.snapshot.excel_layout??'case');}}><option value="">生成时的配置快照</option>{exportOptions?.profiles?.map((p:Json)=><option key={p.id} value={p.id}>{p.name} · 当前版本</option>)}</select></label>{caseExport&&<label>Excel 布局<select value={layout} onChange={e=>setLayout(e.target.value)}><option value="case">一条用例一行</option><option value="step">一个步骤一行</option></select></label>}<ErrorBox message={error}/>{!exportOptions&&<p className="muted">{caseExport?'正在检查模板字段…':'正在读取场景导出格式…'}</p>}{missingFields.length>0&&<div className="report-findings"><p>所选模板有 {missingFields.length} 项必填内容待补全。请先补充所列内容。</p><ul>{missingFields.slice(0,20).map((g:Json)=><li key={g.id+':'+g.field}><strong>{g.id} · {g.header}</strong>：{g.reason||'尚未生成'}</li>)}</ul>{missingFields.length>20&&<p>另有 {missingFields.length-20} 项待补全。</p>}{!chatOnly&&!readOnly?<><button disabled={loading} onClick={completeFields}>补全模板字段</button><button onClick={editMissingFields}>填写缺失字段</button></>:<p className="muted small-text">{readOnly?'请打开最新版本，在聊天中要求补全模板字段，再导出更新后的版本。':'可在聊天中输入“补全当前用例的模板字段”，完成后重新导出。'}</p>}</div>}{exportCheck?.manual_columns?.length>0&&<p className="muted small-text">人工填写：{exportCheck.manual_columns.join('、')}。没有填写时允许留空，不自动生成执行结果。</p>}{exportCheck?.optional_columns?.length>0&&<p className="muted small-text">可选字段：{exportCheck.optional_columns.join('、')}，允许留空。</p>}<div className="dialog-actions"><button className="primary" disabled={loading||!exportOptions||!data.items.length||(scope==='selected'&&!selected.length)||(caseExport&&(!exportCheck||missingFields.length>0))} onClick={async()=>{setLoading(true);try{await downloadArtifact(data.id,caseExport?layout:undefined,exportIds??[],exportProfile||undefined,data.revision);setExporting(false);}catch(e){setError(errText(e));}finally{setLoading(false);}}}><Download size={16}/>下载 XLSX</button></div></Dialog>}
  {evidence&&<Dialog title="需求依据" onClose={()=>setEvidence(null)} wide>{readOnly&&<p className="muted small-text">此处读取当前来源内容。父级采用的历史片段可在对应父级中展开查看。</p>}{evidence.length?evidence.map(({ref,source})=><section className="evidence" key={ref}><strong>{source?.name??'来源'}</strong><small>{ref}</small><p className="preserve">{source?.chunks?.find(c=>c.id===ref)?.text??'该段落当前不可读取，请检查来源。'}</p></section>):<p>当前条目没有需求引用。</p>}</Dialog>}
 </section>;
}

function ArtifactRow({item,kind,readOnly,context,lineageLoading,lineageError,columns,hasReview,checked,expanded,onCheck,onExpand,onEvidence}:{item:Json;kind:string;readOnly:boolean;context:RowContext;lineageLoading:boolean;lineageError?:string;columns:Json[];hasReview:boolean;checked:boolean;expanded:boolean;onCheck:()=>void;onExpand:()=>void;onEvidence:()=>void}){
 const isCase=kind==='cases';const steps=Array.isArray(item.steps)?item.steps:[];const first=steps[0];
 const colSpan=(readOnly?0:1)+6+(isCase?4:0)+columns.length;
 return <><tr className="artifact-data-row">{!readOnly&&<td className="select-col"><input type="checkbox" aria-label={'选择 '+item.id} checked={checked} onChange={onCheck}/></td>}<td className="case-id">{item.id}</td><td className="artifact-title-cell"><button className="table-title" onClick={onExpand}>{item.title??'未命名'}</button>{!isCase&&item.description&&<p className="artifact-cell-preview"><TextValue value={item.description}/></p>}</td><td className="small-text">{item.type??'场景'}</td><td>{item.priority??'—'}</td>{isCase&&<><td className="artifact-preconditions"><div className={expanded?'':'artifact-cell-preview'}><TextValue value={item.preconditions}/></div></td><td className="artifact-step-preview">{expanded?<span className="muted small-text">完整步骤见下方</span>:<TextValue value={typeof first==='string'?first:first?.action}/>}<small>共 {steps.length} 步</small></td><td className="artifact-step-preview">{!expanded&&<TextValue value={first?.expected}/>}</td></>}<td className="artifact-lineage-cell"><ArtifactLineage context={context} kind={kind} loading={lineageLoading} error={lineageError}/></td>{isCase&&<td className="artifact-review-cell"><CaseReview context={context} hasReview={hasReview}/></td>}{columns.map(column=><td key={column.field} className="artifact-custom-cell"><TextValue value={item[column.field]}/></td>)}<td><button className="icon-button" aria-label={'展开 '+item.id} aria-expanded={expanded} onClick={onExpand}>{expanded?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button></td></tr>{expanded&&<tr className="expanded-row"><td colSpan={colSpan}><div className="case-details">{isCase&&item.description&&<p><strong>用例描述：</strong><TextValue value={item.description}/></p>}{!isCase&&item.description&&<p><strong>场景说明：</strong><TextValue value={item.description}/></p>}{isCase&&<table className="case-step-table" aria-label={item.id+' 步骤与预期结果'}><thead><tr><th>步骤</th><th>操作 / Step</th><th>预期结果 / Expected result</th></tr></thead><tbody>{steps.map((step:Json|string,index:number)=><tr key={index}><td>{index+1}</td><td><TextValue value={typeof step==='string'?step:step.action}/></td><td><TextValue value={typeof step==='string'?undefined:step.expected}/></td></tr>)}</tbody></table>}<button className="text-accent" disabled={!item.refs?.length} onClick={onEvidence}><FileText size={15}/>查看这条的需求依据</button><details><summary>全部字段</summary><pre>{JSON.stringify(item,null,2)}</pre></details></div></td></tr>}</>;
}
