import {useEffect,useRef,useState} from 'react';
import {Check,MessageSquare,Sparkles,RefreshCw,Calculator} from 'lucide-react';
import {api,errText} from './api';
import {useConversationCommand} from './conversation';
import {Dialog,ErrorBox,Spinner,TextValue} from './ui';
import type {Artifact,Json} from './types';

type Action='estimate'|'explain'|'modify'|'sync';
const names:Record<Action,string>={estimate:'估算用例数量',explain:'解释或总结用例',modify:'AI 微调',sync:'同步关联用例'};
const presets=[['步骤更清楚','只优化步骤的表达，使每一步操作明确、可执行，并对应可验证的预期结果；不新增需求规则。'],['检查边界条件','根据已有需求检查选中条目的边界条件，仅修正有依据的遗漏；不臆造阈值。'],['统一术语','根据已有需求统一术语和表述，保留业务含义、编号、引用及已有人工填写内容。']];

export function ArtifactActions({artifact,selected,onChanged,onSaved,syncRequest=0}:{artifact:Artifact;selected:string[];onChanged:()=>void;onSaved?:(artifacts:Artifact[])=>void;syncRequest?:number}){
 const command=useConversationCommand();
 const [action,setAction]=useState<Action>();const [instruction,setInstruction]=useState('');const [scope,setScope]=useState<string[]>([]);
 const [workspace,setWorkspace]=useState<Json>();const [showSources,setShowSources]=useState(false);const [sourceIds,setSourceIds]=useState<string[]>([]);const [targets,setTargets]=useState<string[]>([]);const [proposal,setProposal]=useState<Json>();const [originals,setOriginals]=useState<Record<string,Artifact>>({});
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [done,setDone]=useState('');const seq=useRef(0);const lastSync=useRef(0);
 useEffect(()=>()=>{seq.current++;},[]);
 useEffect(()=>{setProposal(undefined);},[artifact.id,artifact.revision]);
 function close(){seq.current++;setAction(undefined);setBusy(false);}
 async function begin(next:Action){const token=++seq.current;setAction(next);setScope([...selected]);setInstruction(next==='estimate'?'仅根据当前场景估算用例数量区间，说明拆分理由和待确认假设，不生成用例。':next==='explain'?(selected.length?'解释选中用例的测试目的、前置条件、操作和预期结果。':'总结这些用例的业务内容、验证重点和已有覆盖，不修改用例。'):next==='sync'?'根据当前场景的最新版本，更新所选场景对应的用例，保留其他用例及已有人工填写内容。':'');setProposal(undefined);setOriginals({});setError('');setDone('');setWorkspace(undefined);setTargets([]);setShowSources(false);setSourceIds([]);setBusy(next==='sync');if(next!=='sync')return;try{const value=await api<Json>('/artifacts/'+artifact.id+'/workspace');if(token===seq.current){setWorkspace(value);const linked=(value.related_artifacts??[]).filter((item:Json)=>item.type==='cases'&&item.linked);setTargets(linked.length===1?[linked[0].id]:[]);}}catch(e){if(token===seq.current)setError(errText(e));}finally{if(token===seq.current)setBusy(false);}}
 useEffect(()=>{if(syncRequest&&syncRequest!==lastSync.current){lastSync.current=syncRequest;void begin('sync');}},[syncRequest]);
 async function loadSources(){setShowSources(true);if(workspace)return;const token=++seq.current;setBusy(true);setError('');try{const value=await api<Json>('/artifacts/'+artifact.id+'/workspace');if(token===seq.current)setWorkspace(value);}catch(e){if(token===seq.current)setError(errText(e));}finally{if(token===seq.current)setBusy(false);}}
 function changeInstruction(value:string){setInstruction(value);setProposal(undefined);setDone('');}
 async function preview(){
  if(!action)return;const token=++seq.current;setBusy(true);setError('');setProposal(undefined);setDone('');
  try{
   const name=action==='estimate'?'artifact.estimate':action==='explain'?'artifact.analyze':action==='sync'?'artifact.sync_related':'artifact.preview';
   const result=await command({name,arguments:{instruction,...(action==='modify'?{action:'modify'}:{}),...(scope.length?{selected_ids:scope}:{}),...(action!=='estimate'&&sourceIds.length?{source_ids:sourceIds}:{}),...(action==='sync'?{related_artifact_ids:targets,preview:true}:{})}},instruction,artifact);
   const difference=result.parts?.find(part=>part.type==='diff');const answer=result.parts?.find(part=>part.type==='answer');const estimate=result.parts?.find(part=>part.type==='estimate');
   const value={id:difference?.type==='diff'?difference.proposal_id:undefined,summary:result.message,changes:difference?.type==='diff'?difference.changes:[],answer:answer?.type==='answer'?answer.text:undefined,refs:answer?.type==='answer'?answer.refs:[],estimate:estimate?.type==='estimate'?estimate.data:undefined};
   const previous:Record<string,Artifact>={[artifact.id]:artifact};
   await Promise.all(value.changes.filter((change:Json)=>!change.before_items&&!previous[change.artifact_id]).map(async(change:Json)=>{previous[change.artifact_id]=await api<Artifact>('/artifacts/'+change.artifact_id+'/revisions/'+change.expected_revision);}));
   if(token===seq.current){setOriginals(previous);setProposal(value);}
  }catch(e){if(token===seq.current)setError(errText(e));}finally{if(token===seq.current)setBusy(false);}
 }
 async function apply(){if(!proposal)return;const token=++seq.current;setBusy(true);setError('');try{const value=await command({name:'artifact.apply',arguments:{proposal_id:proposal.id}},'确认应用这项预览修改',artifact);const artifacts=await Promise.all((value.parts??[]).filter(part=>part.type==='artifact').map(part=>api<Artifact>('/artifacts/'+(part as {artifact_id:string}).artifact_id)));if(token===seq.current){setProposal(undefined);setDone(value.message||'已保存新版本。');onSaved?.(artifacts);onChanged();}}catch(e){if(token===seq.current){setError(errText(e));setProposal(undefined);}}finally{if(token===seq.current)setBusy(false);}}
 async function discard(){if(!proposal?.id)return;setBusy(true);setError('');try{const result=await command({name:'artifact.discard',arguments:{proposal_id:proposal.id}},'取消这项预览修改',artifact);setProposal(undefined);setDone(result.message);onChanged();}catch(e){setError(errText(e));}finally{setBusy(false);}}
 return <><div className="artifact-action-buttons"><button onClick={()=>void begin('modify')}><Sparkles size={15}/>{selected.length?`AI 微调选中 ${selected.length} 条`:'AI 微调'}</button>{artifact.type==='cases'&&<button onClick={()=>void begin('explain')}><MessageSquare size={15}/>{selected.length?'解释选中用例':'总结用例'}</button>}{artifact.type==='scenarios'&&<><button onClick={()=>void begin('estimate')}><Calculator size={15}/>估算用例数量（不生成）</button><button onClick={()=>void begin('sync')}><RefreshCw size={15}/>同步关联用例</button></>}</div>
 {action&&<Dialog title={names[action]+' · '+artifact.title} onClose={()=>{if(!busy)close();}} closeDisabled={busy} wide><p className="action-scope">基于 v{artifact.revision} · {scope.length?`选中 ${scope.length} 条：${scope.join('、')}`:`全部 ${artifact.items.length} 条`}</p>
 {action==='modify'&&<div className="action-presets">{presets.map(([label,text])=><button key={label} disabled={busy} onClick={()=>changeInstruction(text)}>{label}</button>)}</div>}
 <label>本次要求<textarea aria-label="本次微调或分析要求" rows={3} value={instruction} disabled={busy} onChange={e=>changeInstruction(e.target.value)}/></label>
 {action==='sync'&&workspace&&<fieldset className="action-targets"><legend>要同步的用例成果</legend>{(workspace.related_artifacts??[]).filter((item:Json)=>item.type==='cases'&&item.linked).length>1&&<p className="muted small-text">此场景有多套关联用例，请选择本次要同步的成果。</p>}{(workspace.related_artifacts??[]).filter((item:Json)=>item.type==='cases').map((item:Json)=><label key={item.id}><input type="checkbox" checked={targets.includes(item.id)} disabled={busy} onChange={e=>{setTargets(old=>e.target.checked?[...old,item.id]:old.filter(id=>id!==item.id));setProposal(undefined);}}/>{item.title} · v{item.revision} · {item.linked?'已关联':'待选择关联'}</label>)}{!(workspace.related_artifacts??[]).some((item:Json)=>item.type==='cases')&&<p className="muted">当前没有可同步的用例成果。可先生成或导入用例，再选择关联目标。</p>}</fieldset>}
 {action!=='estimate'&&<div className="action-source-picker"><button disabled={busy} onClick={()=>void loadSources()}>添加本次补充资料</button>{showSources&&workspace&&<fieldset className="action-targets"><legend>本次额外参考的资料</legend><p className="muted small-text">勾选需要纳入本次操作的新资料。原成果的需求依据会继续使用。</p>{(workspace.sources??[]).filter((source:Json)=>source.role!=='example').map((source:Json)=><label key={source.id}><input type="checkbox" disabled={busy} checked={sourceIds.includes(source.id)} onChange={e=>{setSourceIds(old=>e.target.checked?[...old,source.id]:old.filter(id=>id!==source.id));setProposal(undefined);setDone('');}}/>{source.name}</label>)}{!(workspace.sources??[]).some((source:Json)=>source.role!=='example')&&<p className="muted">暂无可添加资料。可先在会话中上传补充需求，再打开此操作。</p>}</fieldset>}</div>}
 <ErrorBox message={error}/>{done&&<p role="status" className="action-saved"><Check size={16}/>{done}</p>}
 {proposal&&<section className="action-preview" aria-label="操作预览"><h3>{action==='estimate'?'估算结果':action==='explain'?'用例说明':'变更预览'}</h3><p className="preserve">{proposal.summary}</p>{proposal.answer&&<p className="preserve"><TextValue value={proposal.answer}/></p>}{proposal.refs?.length>0&&<p className="muted small-text">需求依据：{proposal.refs.join('、')}</p>}{proposal.estimate&&<><p><strong>预计 {proposal.estimate.min_count}–{proposal.estimate.max_count} 条用例</strong> · 仅估算，未生成用例</p><div className="table-scroll"><table><thead><tr><th>场景</th><th>数量区间</th><th>拆分理由</th><th>待确认假设</th></tr></thead><tbody>{(proposal.estimate.scenarios??[]).map((item:Json)=><tr key={item.scenario_id}><td>{item.scenario_id}</td><td>{item.min_count}–{item.max_count}</td><td><TextValue value={item.rationale}/></td><td>{(item.assumptions??[]).join('；')||'无额外假设'}</td></tr>)}</tbody></table></div></>}{(proposal.changes??[]).map((change:Json)=><ChangePreview key={change.artifact_id} change={change} before={originals[change.artifact_id]}/>)}{(action==='modify'||action==='sync')&&!(proposal.changes??[]).length&&<p>没有需要保存的变更。</p>}</section>}
 <div className="dialog-actions"><button disabled={busy||!instruction.trim()||(action==='sync'&&(!workspace||!targets.length))} onClick={()=>void preview()}>{busy?<Spinner/>:<Sparkles size={16}/>} {action==='estimate'?'开始估算':action==='explain'?'生成说明':proposal?'重新预览':'预览修改'}</button>{proposal&&['modify','sync'].includes(action)&&(proposal.changes??[]).length>0&&<button className="primary" disabled={busy} onClick={()=>void apply()}><Check size={16}/>确认应用修改</button>}{proposal?.id&&<button disabled={busy} onClick={()=>void discard()}>取消此修改</button>}<button onClick={close} disabled={busy}>关闭</button></div></Dialog>}
 </>;
}

export function ChangePreview({change,before}:{change:Json;before?:Artifact}){
 const prior=new Map<string,Json>((before?.items??change.before_items??[]).map((item:Json)=>[item.id,item]));const next=new Map((change.items??[]).map((item:Json)=>[item.id,item])) as Map<string,Json>;
 const ids=[...new Set([...prior.keys(),...next.keys()])];const altered=ids.filter(id=>JSON.stringify(prior.get(id))!==JSON.stringify(next.get(id)));
 return <section className="artifact-change"><h4>{change.title??before?.title??change.artifact_id} · v{change.expected_revision} → 新版本</h4><p className="muted small-text">新增 {ids.filter(id=>!prior.has(id)).length} · 更新 {ids.filter(id=>prior.has(id)&&next.has(id)&&JSON.stringify(prior.get(id))!==JSON.stringify(next.get(id))).length} · 删除 {ids.filter(id=>!next.has(id)).length}</p>{altered.map(id=>{const old=prior.get(id),item=next.get(id);const fields=[...new Set([...Object.keys(old??{}),...Object.keys(item??{})])].filter(key=>JSON.stringify(old?.[key])!==JSON.stringify(item?.[key]));const operation=(change.operations??[]).find((op:Json)=>op.id===id&&op.op==='delete');return <div className="item-change" key={id}><strong>{id} · {item?.title??old?.title} · {!old?'新增':!item?'删除':'更新'}</strong>{operation&&<p className="action-deletion-reason">删除原因：{operation.reason} · 依据：{(operation.refs??[]).join('、')||'未提供'}</p>}<div className="table-scroll"><table><thead><tr><th>字段</th><th>修改前</th><th>修改后</th></tr></thead><tbody>{fields.map(field=><tr key={field}><th>{({title:'标题',description:'描述',preconditions:'前置条件',steps:'步骤 / 预期结果',priority:'优先级',type:'类型',refs:'需求依据',scenario_id:'关联场景'} as Record<string,string>)[field]??field}</th><td><FieldValue field={field} value={old?.[field]}/></td><td><FieldValue field={field} value={item?.[field]}/></td></tr>)}</tbody></table></div></div>;})}{change.report&&JSON.stringify(change.report)!==JSON.stringify(before?.report)&&<details><summary>报告变更</summary><div className="action-report-diff"><div><strong>修改前</strong><pre>{JSON.stringify(before?.report??{},null,2)}</pre></div><div><strong>修改后</strong><pre>{JSON.stringify(change.report,null,2)}</pre></div></div></details>}</section>;
}
function FieldValue({field,value}:{field:string;value:unknown}){if(field==='steps'&&Array.isArray(value))return <ol className="action-step-list">{value.map((step:Json,i:number)=><li key={i}><p><strong>操作：</strong><TextValue value={step.action}/></p><p><strong>预期：</strong><TextValue value={step.expected}/></p></li>)}</ol>;return <TextValue value={value}/>;}
