import {useEffect,useState} from 'react';
import {Check,ChevronDown,ChevronUp,Download,FileText,History,MessageSquare,PenLine,Plus,Trash2} from 'lucide-react';
import {AnalysisReport} from './AnalysisReport';
import {TemplateUsage} from './TemplateUsage';
import {ArtifactActions} from './ArtifactActions';
import {WorkspaceCoverage} from './WorkspaceCoverage';
import {PinSamples} from './ProjectSamples';
import {canEditItems,ItemEditor} from './ItemEditor';
import {api,downloadArtifact,errText} from './api';
import {Dialog,ErrorBox,Spinner,TextValue} from './ui';
import type {Artifact,Json,Source} from './types';

export function ArtifactCard({id,refreshKey,onTarget,onChanged,compact=false,onOpen,initialDetailsOpen=false}:{id:string;refreshKey?:string;onTarget:(artifact:Artifact,selected:string[])=>void;onChanged:()=>void;compact?:boolean;onOpen?:(artifact:Artifact)=>void;initialDetailsOpen?:boolean}){
 const [data,setData]=useState<Artifact>();const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 const [selected,setSelected]=useState<string[]>([]);const [expanded,setExpanded]=useState<string>();
 const [expandAll,setExpandAll]=useState<boolean|undefined>();const [scenarioSaved,setScenarioSaved]=useState(false);const [syncRequest,setSyncRequest]=useState(0);
 useEffect(()=>{setExpandAll(undefined);setExpanded(undefined);setScenarioSaved(false);},[id]);
 const [reportDraft,setReportDraft]=useState<Json>({});
 const [editor,setEditor]=useState(false);const [baseRevision,setBaseRevision]=useState(0);const [editorMode,setEditorMode]=useState('form');const [draft,setDraft]=useState('');const [history,setHistory]=useState<Json[]|null>(null);
 const [historyItem,setHistoryItem]=useState<Artifact>();const [exporting,setExporting]=useState(false);
 const [exportOptions,setExportOptions]=useState<Json>();const [exportProfile,setExportProfile]=useState('');
 useEffect(()=>{if(!exporting)return;let active=true;setExportOptions(undefined);api('/artifacts/'+id+'/export-options').then(v=>{if(active){setExportOptions(v);const chosen=v.profiles?.find((p:Json)=>p.id===exportProfile);setLayout(chosen?.config.excel_layout??v.snapshot.excel_layout??'case');}}).catch(e=>active&&setError(errText(e)));return()=>{active=false;};},[exporting,id,refreshKey]);
 const [layout,setLayout]=useState('case');const [scope,setScope]=useState('all');const [evidence,setEvidence]=useState<{ref:string;source:Source}[]|null>(null);
 useEffect(()=>{let alive=true;api<Artifact>('/artifacts/'+id).then(value=>{if(alive){setData(value);setSelected(old=>old.filter(item=>value.items.some(x=>x.id===item)));setError('');}}).catch(e=>alive&&setError(errText(e)));return()=>{alive=false;};},[id,refreshKey]);
 async function save(){if(!data)return;setError('');setLoading(true);try{const items=JSON.parse(draft);if(!Array.isArray(items))throw new Error('内容必须是 JSON 数组');setData(await api('/artifacts/'+id,{expected_revision:baseRevision,items,...(data.type==='analysis'?{report:reportDraft}:{})},'PUT'));setEditor(false);if(data.type==='scenarios')setScenarioSaved(true);onChanged();}catch(e){setError(errText(e));}finally{setLoading(false);}}
 async function showEvidence(refs:string[]){setLoading(true);setError('');try{const ids=[...new Set(refs.map(ref=>ref.split('#')[0]))];const sources=await Promise.all(ids.map(sourceId=>api<Source>('/sources/'+encodeURIComponent(sourceId))));setEvidence(refs.map(ref=>({ref,source:sources.find(s=>s.id===ref.split('#')[0])!})));}catch(e){setError(errText(e));}finally{setLoading(false);}}
 async function showHistory(){setError('');try{setHistory(await api('/artifacts/'+id+'/revisions'));setHistoryItem(undefined);}catch(e){setError(errText(e));}}
 async function restore(){if(!historyItem||!data)return;setLoading(true);try{setData(await api('/artifacts/'+id+'/restore',{revision:historyItem.revision,expected_revision:data.revision}));setHistory(null);onChanged();}catch(e){setError(errText(e));}finally{setLoading(false);}}
 const caseExport=data?.type==='cases';
 const exportCheck=caseExport?(exportProfile?exportOptions?.profiles?.find((p:Json)=>p.id===exportProfile)?.field_check:exportOptions?.snapshot_check):undefined;
 const missingFields=(exportCheck?.missing??[]).filter((gap:Json)=>scope!=='selected'||selected.includes(gap.id));
 async function completeFields(){if(!data)return;setLoading(true);setError('');try{await api('/artifacts/'+id+'/complete-fields',{expected_revision:data.revision,...(exportProfile?{profile_id:exportProfile}:{}),...(scope==='selected'?{selected_ids:selected}:{})});setExporting(false);onChanged();}catch(e){setError(errText(e));}finally{setLoading(false);}}
 function editMissingFields(){if(!data)return;setDraft(JSON.stringify(data.items,null,2));setBaseRevision(data.revision);setEditorMode('form');setExporting(false);setEditor(true);}
 const allDetailsOpen=expandAll??(initialDetailsOpen||!!data?.report?.review_reports?.length);
 const allRefs=[...new Set(data?.items.flatMap(item=>item.refs??[])??[])] as string[];
 if(!data)return <div className="artifact"><ErrorBox message={error}/>{!error&&<p className="muted inline"><Spinner/> 正在读取产物…</p>}</div>;
 if(data.type==='answer')return null;
 if(compact)return <button className="artifact-preview" aria-label={'打开成果 · '+data.title} onClick={()=>onOpen?.(data)}><span className="artifact-preview-icon"><FileText size={22}/></span><span><strong>{data.title}</strong><small>{data.items.length} 条 · v{data.revision} · 查看详情、编辑和导出</small></span><ChevronDown size={17} className="artifact-preview-arrow"/></button>;
 return <section className="artifact" aria-label={data.title}>
  <div className="artifact-head"><div><h3>{data.title}</h3><span className="muted small-text">{data.items.length} 条 · v{data.revision}</span></div><div className="actions"><button onClick={()=>{setReportDraft(data.report??{});setDraft(JSON.stringify(data.items,null,2));setBaseRevision(data.revision);setEditorMode(canEditItems(data.items,data.type)?'form':'json');setEditor(true);setError('');}}><PenLine size={16}/>编辑</button><button onClick={showHistory}><History size={16}/>历史版本</button>{['cases','scenarios'].includes(data.type)&&<button className="text-accent" onClick={()=>{setError('');setScope(selected.length?'selected':'all');setExporting(true);}}><Download size={16}/>导出 Excel</button>}</div></div>
  <ErrorBox message={error}/>
  {data.report?.template_usage&&<TemplateUsage usage={data.report.template_usage}/>}
  <ArtifactActions artifact={data} selected={selected} onChanged={onChanged} syncRequest={syncRequest} onSaved={artifacts=>{const current=artifacts.find(item=>item.id===id);if(current){setData(current);if(current.type==='scenarios')setScenarioSaved(true);}}}/>
  {data.type==='cases'&&<PinSamples artifact={data} selectedIds={selected} onChanged={onChanged}/>}
  {scenarioSaved&&data.type==='scenarios'&&<div className="scenario-saved-actions"><span>场景新版本已保存，可查看并预览关联用例的调整。</span><button onClick={()=>setSyncRequest(x=>x+1)}>查看影响 / 同步关联用例</button><button className="icon-button" aria-label="收起场景保存提示" onClick={()=>setScenarioSaved(false)}>×</button></div>}
  {data.type==='cases'&&<div className="artifact-table-tools"><span className="muted small-text">{selected.length?`已选择 ${selected.length} 条，可单独微调或解释`:'勾选用例可限定微调和解释范围'}</span><button onClick={()=>{setExpandAll(!allDetailsOpen);setExpanded(undefined);}}>{allDetailsOpen?'收起全部步骤':'展开全部步骤'}</button></div>}
  {['cases','scenarios'].includes(data.type)?<div className="table-scroll"><table><thead><tr><th className="select-col"><input type="checkbox" aria-label="选择全部条目" checked={!!data.items.length&&selected.length===data.items.length} onChange={e=>setSelected(e.target.checked?data.items.map(item=>item.id):[])}/></th><th>编号</th><th>标题</th><th>类型</th><th>优先级</th><th aria-label="展开"/></tr></thead><tbody>{data.items.map(item=><ArtifactRow key={item.id} item={item} checked={selected.includes(item.id)} expanded={allDetailsOpen||expanded===item.id} onCheck={()=>setSelected(old=>old.includes(item.id)?old.filter(x=>x!==item.id):[...old,item.id])} onExpand={()=>{if(allDetailsOpen){setExpandAll(false);setExpanded(undefined);}else setExpanded(expanded===item.id?undefined:item.id);}} onEvidence={()=>showEvidence(item.refs??[])}/>)}</tbody></table></div>:<div className="artifact-content">{data.items.map((item,index)=><div key={item.id??index} className="analysis-item"><strong>{item.title??item.id??'结果'}</strong><p><TextValue value={item.description??item.answer??item.content??item}/></p>{item.refs?.length>0&&<button className="text-accent" onClick={()=>showEvidence(item.refs)}><FileText size={14}/>需求依据 · {item.refs.length}</button>}</div>)}</div>}
  {data.report&&Object.keys(data.report).length>0&&<details className="coverage-details"><summary>需求理解、覆盖说明与待确认项{data.report.unresolved_rows?.length?` · ${data.report.unresolved_rows.length} 条待修复`:""}</summary><AnalysisReport report={data.report}/></details>}
  <WorkspaceCoverage artifactId={data.id} revision={data.revision} artifactType={data.type}/>
  <div className="artifact-foot"><button className="text-accent" disabled={!allRefs.length||loading} onClick={()=>showEvidence(allRefs)}><FileText size={16}/>查看需求依据</button><button disabled={!data.items.length} onClick={()=>onTarget(data,selected)}><MessageSquare size={15}/>{selected.length?`让 AI 修改选中 ${selected.length} 条`:'让 AI 修改此结果'}</button></div>
  {editor&&<Dialog title={'编辑 · '+data.title} onClose={()=>setEditor(false)} wide><p className="muted">修改标题、前置条件、操作或预期结果后，保存为新版本。未编辑的内容会保留。</p><div className="tabs"><button className={editorMode==='form'?'active':''} onClick={()=>{try{const value=JSON.parse(draft);if(!canEditItems(value,data.type))throw new Error();setEditorMode('form');setError('');}catch{setError('请先修正 JSON：每个条目必须是对象并包含 id，文本字段必须为字符串，refs 必须为字符串数组，用例 steps 必须是步骤对象数组。');}}}>表单编辑</button><button className={editorMode==='json'?'active':''} onClick={()=>setEditorMode('json')}>JSON · 全部字段</button></div>{editorMode==='json'?<textarea className="code-editor" aria-label="产物 JSON" value={draft} onChange={e=>setDraft(e.target.value)} spellCheck={false}/>:<ItemEditor items={JSON.parse(draft)} kind={data.type} columns={exportCheck?.columns??data.report?.template_usage?.field_contract??data.report?.template_usage?.columns} onChange={items=>setDraft(JSON.stringify(items,null,2))}/>}{data.type==='analysis'&&<div><label>需求理解摘要<textarea aria-label="需求理解摘要" value={reportDraft.summary??''} onChange={e=>setReportDraft({...reportDraft,summary:e.target.value})}/></label>{Array.isArray(reportDraft.diagrams)&&reportDraft.diagrams.map((d:Json,i:number)=><label key={i}>{d.title??'业务图'} · Mermaid<textarea aria-label={'图形源码 '+(i+1)} rows={6} value={d.mermaid??''} onChange={e=>setReportDraft({...reportDraft,diagrams:reportDraft.diagrams.map((x:Json,j:number)=>i===j?{...x,mermaid:e.target.value}:x)})}/></label>)}</div>}<p className="muted small-text">当前草稿基于 v{baseRevision}。</p><ErrorBox message={error}/>{error&&<button onClick={async()=>{try{const latest=await api<Artifact>('/artifacts/'+id);setData(latest);setDraft(JSON.stringify(latest.items,null,2));setBaseRevision(latest.revision);setError('');}catch(e){setError(errText(e));}}}>放弃草稿，载入最新版本</button>}<div className="dialog-actions"><button onClick={()=>{try{const items=JSON.parse(draft);items.push({id:'NEW-'+Date.now(),title:'新条目',refs:allRefs.slice(0,1),...(data.type==='cases'?{scenario_id:data.items[0]?.scenario_id??'',type:'Business',priority:'P2',preconditions:'',steps:[{action:'',expected:''}]}:{description:'',priority:'P2'})});setDraft(JSON.stringify(items,null,2));}catch{setError('请先修正 JSON 格式');}}}><Plus size={16}/>添加条目</button><button className="primary" disabled={loading} onClick={save}>{loading?<Spinner/>:<Check size={16}/>}保存新版本</button></div></Dialog>}
  {history&&<Dialog title="版本历史" onClose={()=>setHistory(null)} wide><div className="history-list">{history.map(item=><button key={item.revision} className={historyItem?.revision===item.revision?'selected':''} onClick={async()=>{try{setHistoryItem(await api('/artifacts/'+id+'/revisions/'+item.revision));}catch(e){setError(errText(e));}}}>v{item.revision}<span>{item.reason??'内容更新'}</span><small>{new Date(item.created_at).toLocaleString()}</small></button>)}</div>{historyItem&&<><pre className="json-preview">{JSON.stringify(historyItem.items,null,2)}</pre><details><summary>本次变更</summary><pre>{JSON.stringify(history.find(item=>item.revision===historyItem.revision)?.diff,null,2)}</pre></details><div className="dialog-actions"><span className="muted">恢复会创建新版本。</span><button className="primary" disabled={loading||historyItem.revision===data.revision} onClick={restore}>恢复此版本</button></div></>}<ErrorBox message={error}/></Dialog>}
  {exporting&&<Dialog title={caseExport?'导出测试用例':'导出测试场景'} onClose={()=>setExporting(false)}><label>导出范围<select value={scope} onChange={e=>setScope(e.target.value)}><option value="all">全部 {data.items.length} 条{caseExport?'用例':'场景'}</option><option value="selected" disabled={!selected.length}>选中 {selected.length} 条{caseExport?'用例':'场景'}</option></select></label><label>导出格式 Profile<select value={exportProfile} onChange={e=>{setExportProfile(e.target.value);const p=exportOptions?.profiles?.find((p:Json)=>p.id===e.target.value);setLayout(p?.config.excel_layout??exportOptions?.snapshot.excel_layout??'case');}}><option value="">生成时的配置快照</option>{exportOptions?.profiles?.map((p:Json)=><option key={p.id} value={p.id}>{p.name} · 当前版本</option>)}</select></label>{caseExport&&<label>Excel 布局<select value={layout} onChange={e=>setLayout(e.target.value)}><option value="case">一条用例一行</option><option value="step">一个步骤一行</option></select></label>}<ErrorBox message={error}/>{!exportOptions&&<p className="muted">{caseExport?'正在检查模板字段…':'正在读取场景导出格式…'}</p>}{missingFields.length>0&&<div className="report-findings"><p>所选模板有 {missingFields.length} 项必填内容待补全。仅处理缺失字段，保留已有用例。</p><ul>{missingFields.slice(0,20).map((g:Json)=><li key={g.id+':'+g.field}><strong>{g.id} · {g.header}</strong>：{g.reason||'尚未生成'}</li>)}</ul>{missingFields.length>20&&<p>另有 {missingFields.length-20} 项待补全。</p>}<button disabled={loading} onClick={completeFields}>补全模板字段</button><button onClick={editMissingFields}>填写缺失字段</button></div>}{exportCheck?.manual_columns?.length>0&&<p className="muted small-text">人工填写：{exportCheck.manual_columns.join('、')}。没有填写时允许留空，不自动生成执行结果。</p>}{exportCheck?.optional_columns?.length>0&&<p className="muted small-text">可选字段：{exportCheck.optional_columns.join('、')}，允许留空。</p>}<div className="dialog-actions"><button className="primary" disabled={loading||!exportOptions||(scope==='selected'&&!selected.length)||(caseExport&&(!exportCheck||missingFields.length>0))} onClick={async()=>{setLoading(true);try{await downloadArtifact(id,caseExport?layout:undefined,scope==='selected'?selected:[],exportProfile||undefined);setExporting(false);}catch(e){setError(errText(e));}finally{setLoading(false);}}}><Download size={16}/>下载 XLSX</button></div></Dialog>}
  {evidence&&<Dialog title="需求依据" onClose={()=>setEvidence(null)} wide>{evidence.length?evidence.map(({ref,source})=><section className="evidence" key={ref}><strong>{source?.name??'来源'}</strong><small>{ref}</small><p className="preserve">{source?.chunks?.find(c=>c.id===ref)?.text??'该段落当前不可读取，请检查来源。'}</p></section>):<p>当前条目没有需求引用。</p>}</Dialog>}
 </section>;
}

function ArtifactRow({item,checked,expanded,onCheck,onExpand,onEvidence}:{item:Json;checked:boolean;expanded:boolean;onCheck:()=>void;onExpand:()=>void;onEvidence:()=>void}){
 return <><tr><td><input type="checkbox" aria-label={'选择 '+item.id} checked={checked} onChange={onCheck}/></td><td className="case-id">{item.id}</td><td><button className="table-title" onClick={onExpand}>{item.title??'未命名'}</button></td><td className="small-text">{item.type??'场景'}</td><td>{item.priority??'—'}</td><td><button className="icon-button" aria-label={'展开 '+item.id} onClick={onExpand}>{expanded?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button></td></tr>{expanded&&<tr className="expanded-row"><td colSpan={6}><div className="case-details">{item.preconditions&&<p><strong>前置条件：</strong><TextValue value={item.preconditions}/></p>}{item.description&&<p><strong>用例描述：</strong><TextValue value={item.description}/></p>}{Array.isArray(item.steps)&&<table className="case-step-table" aria-label={item.id+' 步骤与预期结果'}><thead><tr><th>步骤</th><th>操作 / Step</th><th>预期结果 / Expected result</th></tr></thead><tbody>{item.steps.map((step:Json,index:number)=><tr key={index}><td>{index+1}</td><td><TextValue value={typeof step==='string'?step:step.action}/></td><td><TextValue value={step.expected}/></td></tr>)}</tbody></table>}<button className="text-accent" disabled={!item.refs?.length} onClick={onEvidence}><FileText size={15}/>查看这条的需求依据</button><details><summary>全部字段</summary><pre>{JSON.stringify(item,null,2)}</pre></details></div></td></tr>}</>;
}
