import {createRoot} from 'react-dom/client';
import {App} from './App';
import './styles.css';
import './artifact-actions.css';
import './chat-estimate.css';
import './conversation-layout.css';
import './artifact-lineage.css';
import './project-knowledge.css';
import './field-drift.css';
createRoot(document.getElementById('root')!).render(<App/>);
