import {useEffect,useState} from 'react';
import {Check,RotateCcw,Square} from 'lucide-react';
import {api,errText} from './api';
import {ArtifactCard} from './ArtifactCard';
import {RunTimeline} from './RunTimeline';
import {ErrorBox,Spinner} from './ui';
import type {Artifact,Run} from './types';

const stages:Record<string,string>={input_check:'检查资料用途',source_review:'确认本轮需求资料',summarizing:'整理 AI 总结',understand:'理解需求与业务图',understanding_gate:'确认理解与方案',apply_answer:'应用澄清',dispatch:'识别任务',publish:'保存结果',planning:'制定测试计划',agent_plan:'调整测试计划',agent_analyze:'理解业务与建立流程图',strategy_review:'确认测试方向',coverage:'检查覆盖缺口',agent_summary:'整理本轮结论',routing:'理解你的请求',requirement_analysis:'分析需求',applying_clarification:'应用澄清信息',scenario_generation:'生成测试场景',case_generation:'设计测试用例',case_import:'读取已有用例',case_review:'评审与优化',publishing:'保存最终结果',resuming:'恢复任务',retrying:'重试失败阶段',route:'理解你的请求',analyze:'分析需求',analyze_requirement:'分析需求',analysis:'分析需求',clarify:'等待需求澄清',clarification:'等待需求澄清',scenarios:'生成测试场景',generate_scenarios:'生成测试场景',scenario_review:'等待场景确认',cases:'设计测试用例',generate_cases:'设计测试用例',review:'评审与优化',review_cases:'评审与优化',finalize:'保存最终结果',complete:'已完成',done:'已完成',query:'检索需求证据',learn_template:'学习模板',modify:'修改产物',queued:'等待执行'};
export function RunCard({run,onChanged,onTarget,onSettings,interactionBusy=false}:{run:Run;onChanged:()=>void;onTarget:(artifact:Artifact,ids:string[])=>void;onSettings?:()=>void;interactionBusy?:boolean}){
 const [clock,setClock]=useState(Date.now());
 const [confirmedDepth,setConfirmedDepth]=useState('');
 const [chosenSources,setChosenSources]=useState<string[]>([]);
 const [answer,setAnswer]=useState('');const [error,setError]=useState('');const [working,setWorking]=useState(false);
 const suggestions=(run.interrupt?.question_suggestions??[]).filter(item=>run.interrupt?.questions?.includes(item.question));
 const suggestionText=(question:string,value:string)=>`问题：${question}\n回答：${value}`;
 const adoptSuggestions=(items:typeof suggestions)=>setAnswer(current=>{
  const questions=new Set<string>();
  const blocks=items.filter(item=>{
   if(questions.has(item.question)||current.includes(`问题：${item.question}\n`))return false;
   questions.add(item.question);return true;
  }).map(item=>suggestionText(item.question,item.answer));
  return blocks.length?[current,...blocks].filter(Boolean).join('\n\n'):current;
 });
 async function action(name:string,body:object={}){setError('');setWorking(true);try{await api('/runs/'+run.id+'/'+name,body);setAnswer('');onChanged();}catch(e){setError(errText(e));}finally{setWorking(false);}}
 useEffect(()=>{if(run.interrupt?.type==='source_review')setAnswer(run.interrupt.suggested_text??'');},[run.id,run.interrupt?.type]);
 const agentMode=run.experience==='agent'||run.graph_version===2;
 const pending=run.status==='queued'||run.status==='running';const pause=run.status==='waiting';
 const confirmationBusy=working||interactionBusy||!!run.edit_in_progress;
 useEffect(()=>{if(!pending)return;const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer);},[pending]);
 const detail=run.diagnostic;const waiting=!!detail&&['model.start','model.waiting','model.transport_start'].includes(detail.event);
 const seconds=(value:number)=>Math.max(0,Math.floor(value/1000));
 const elapsed=run.created_at?seconds(clock-Date.parse(run.created_at)):undefined;
 const modelElapsed=detail?seconds((detail.elapsed_ms??0)+Math.max(0,clock-Date.parse(detail.at))):0;
 if(run.status==='completed')return null;
 return <section className={'run-card '+(run.status==='failed'?'failed':'')} aria-live="polite"><div className="run-heading"><span className="inline">{pending?<Spinner/>:<span className={'status-dot '+run.status}/>}<strong>{pending?(stages[run.stage]??'正在处理'):pause?'需要你确认':run.status==='failed'?'任务暂停：处理失败':'任务已停止'}</strong></span><div className="actions">{run.status==='failed'&&<button disabled={working} onClick={()=>action('retry')}><RotateCcw size={15}/>重试未完成步骤</button>}{(pending||pause)&&<button disabled={working} onClick={()=>action('cancel')}><Square size={13}/>停止</button>}</div></div>
 {run.status==='failed'&&<a className="text-accent run-log-link" href={'/api/runs/'+encodeURIComponent(run.id)+'/failed-step'} download>下载失败步骤日志（精简，≤64 KB）</a>}
 {run.generation_plan&&<p className="muted small-text">{run.generation_plan.reason}{run.generation_plan.input_groups>1?` · ${run.generation_plan.input_groups} 个分组`:''}</p>}
 {run.progress&&<div className="count-progress"><div><strong>{run.progress.label}</strong><span>{run.progress.total>1?`已完成 ${run.progress.completed} / ${run.progress.total}`:run.status==='waiting'?'等待你确认':run.status==='failed'?'已暂停':'处理中'}</span></div><progress max={Math.max(1,run.progress.total)} value={run.progress.completed}/>{run.status==='failed'&&run.error&&<p className="error-text">失败：{run.error}</p>}</div>}
 {pending&&<div className="run-progress"><p className="muted small-text">{elapsed!==undefined?`本轮已运行 ${elapsed} 秒。`:''}任务在本机后台执行，可以关闭此页面后再回来。</p>{detail?.batch_count&&<p className="small-text">第 {detail.batch_index}/{detail.batch_count} 批需求</p>}{waiting&&<p className="small-text">等待模型响应 · 本次请求 {modelElapsed} 秒{detail.timeout_seconds?` · 超时设置 ${detail.timeout_seconds} 秒`:''}{detail.attempt?` · 第 ${detail.attempt}/${detail.max_attempts} 次尝试`:''}</p>}{detail?.event==='model.retry'&&<p className="small-text">上次模型请求失败，准备第 {detail.next_attempt} 次尝试。</p>}</div>}
 {run.recovery&&<div className="recovery-guide"><strong>{run.recovery.title}</strong><p>{run.recovery.detail}</p><ul>{run.recovery.suggestions.map((suggestion,index)=><li key={index}>{suggestion}</li>)}</ul>{run.recovery.preserved.length>0&&<p className="preserved-progress">已保留：{run.recovery.preserved.join('、')}</p>}{onSettings&&['authentication','configuration','connection','model','transport','network'].includes(run.recovery.category)&&<button onClick={onSettings}>打开模型设置</button>}</div>}
 {run.error&&!run.recovery&&!run.progress&&<p className="preserve error-text">{run.error}</p>}
 <RunTimeline runId={run.id} restartKey={run.status} onChanged={onChanged} agentMode={agentMode} initialAgent={run.agent} initialOpen={true}/>
 {pause&&run.interrupt?.type==='source_review'&&<div className="clarification"><p>{run.interrupt.message}</p>{run.interrupt.sources?.map(source=><label className="check-label" key={source.id}><input type="checkbox" checked={chosenSources.includes(source.id)} onChange={e=>setChosenSources(old=>e.target.checked?[...old,source.id]:old.filter(id=>id!==source.id))}/>{source.name} · 本轮作为需求使用</label>)}<textarea aria-label="补充需求正文" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="也可以直接粘贴需求正文"/><button className="primary" disabled={working||(!chosenSources.length&&!answer.trim())} onClick={()=>action('resume',{source_ids:chosenSources,answer})}>确认资料，继续当前任务</button></div>}
 {pause&&run.interrupt?.type==='clarification'&&<div className="clarification"><p>以下信息会影响测试设计，请补充后继续。</p>{suggestions.length>0&&<button disabled={confirmationBusy} onClick={()=>adoptSuggestions(suggestions)}>采用全部建议</button>}<ol>{run.interrupt.questions?.map((question,index)=>{const suggestion=suggestions.find(item=>item.question===question);return <li key={index}><p>{question}</p>{suggestion&&<div className="answer-suggestion"><strong>{suggestion.confidence==='supported'?'需求中已有答案':'建议假设'}</strong><p>{suggestion.answer}</p><small>依据：{suggestion.basis}</small>{suggestion.refs.length>0&&<small className="preserve">引用：{suggestion.refs.join(' · ')}</small>}<button disabled={confirmationBusy} onClick={()=>adoptSuggestions([suggestion])}>采用此答案</button></div>}</li>;})}</ol><p className="muted small-text">采用后仅填入下方草稿；已填写的问题会保留，可修改后提交。</p><textarea aria-label="回答澄清问题" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="输入你的确认或补充说明…" rows={4}/><button className="primary" disabled={working||!answer.trim()} onClick={()=>action('resume',{answer})}><Check size={16}/>提交并继续</button></div>}
 {pause&&run.interrupt?.type==='strategy_review'&&<div className="strategy-review"><p>请检查需求理解、业务图与测试范围。可以直接编辑，或通过聊天修订，然后确认生成场景。</p>{run.interrupt.artifact_id&&<ArtifactCard id={run.interrupt.artifact_id} refreshKey={run.updated_at} onTarget={onTarget} onChanged={onChanged}/>}<label>本轮测试深度<select aria-label="确认测试深度" value={confirmedDepth} onChange={e=>setConfirmedDepth(e.target.value)}><option value="">沿用本轮 Profile</option><option value="quick">Quick · 核心路径</option><option value="standard">Standard · 主要规则</option><option value="deep">Deep · 深入组合</option></select></label>{confirmationBusy&&<p className="small-text">正在保存 AI 修改，保存完成后才能确认。</p>}<button className="primary" disabled={confirmationBusy} onClick={()=>action('resume',{approved:true,...(confirmedDepth?{depth:confirmedDepth}:{})})}><Check size={16}/>确认理解，生成场景</button></div>}
 {pause&&run.interrupt?.type==='scenario_review'&&<div className="scenario-review"><p>请检查场景。可以直接编辑，确认后将使用最新版本生成用例。</p>{run.interrupt.artifact_id&&<ArtifactCard id={run.interrupt.artifact_id} refreshKey={run.updated_at} onTarget={onTarget} onChanged={onChanged}/>} {confirmationBusy&&<p className="small-text">AI 正在修改当前场景，保存后才能确认。</p>}<button className="primary" disabled={confirmationBusy} onClick={()=>action('resume',{approved:true})}><Check size={16}/>确认场景，继续生成用例</button></div>}
 <details className="run-diagnostics"><summary>运行详情</summary><p className="small-text">任务：{run.id}<br/>阶段：{run.stage}{detail?.node?` · 节点：${detail.node}`:''}</p>{detail&&<><p className="small-text">最近事件：{detail.event} · {new Date(detail.at).toLocaleTimeString()}</p><pre>{JSON.stringify(detail,null,2)}</pre></>}<a className="text-accent" href={'/api/runs/'+encodeURIComponent(run.id)+'/debug-bundle'} download>下载完整诊断包</a><p className="muted small-text">诊断包包含本轮发送内容、原始回答、校验错误和检查点，不含模型认证请求头。</p></details><ErrorBox message={error}/></section>;
}
