import {cloudRuntime} from './runtime';
import {useEffect,useState} from 'react';
import {Check,PlugZap,Plus,Save} from 'lucide-react';
import {api,errText} from './api';
import {Dialog,ErrorBox,Spinner} from './ui';
import type {Json,Profile,Settings} from './types';

export function SettingsDialog({projectId,profiles,activeProfileId,proposal,onClose,onSaved}:{projectId:string;profiles:Profile[];activeProfileId:string;proposal?:Json;onClose:()=>void;onSaved:()=>void}){
 const [tab,setTab]=useState(proposal?'profile':'model');const [settings,setSettings]=useState<Settings>();const [key,setKey]=useState('');const [clearKey,setClearKey]=useState(false);
 const initialProfile=profiles.find(p=>p.id===activeProfileId)??profiles[0];const [profileId,setProfileId]=useState(initialProfile?.id??'');const [name,setName]=useState(initialProfile?.name??'Default Profile');const [config,setConfig]=useState(JSON.stringify(proposal??initialProfile?.config??{},null,2));
 const [error,setError]=useState('');const [notice,setNotice]=useState('');const [working,setWorking]=useState(false);
 useEffect(()=>{api<Settings>('/settings').then(setSettings).catch(e=>setError(errText(e)));},[]);
 async function saveModel(test=false){if(!settings)return;setWorking(true);setError('');setNotice('');try{if(!settings.environment_managed){const updated=await api<Settings>('/settings',{provider:settings.provider,base_url:settings.base_url,model:settings.model,timeout_seconds:settings.timeout_seconds,...(key?{api_key:key}:{}),...(clearKey?{clear_api_key:true}:{})},'PUT');setSettings(updated);setKey('');setClearKey(false);}if(test){const result=await api('/settings/test',{});if(!result.ok)throw new Error(result.message);setNotice(result.message||'连接成功');}else setNotice(cloudRuntime?'模型配置已保存，API Key 已加密保存':'模型配置已保存在本机');onSaved();}catch(e){setError(errText(e));}finally{setWorking(false);}}
 async function saveProfile(create=false){setWorking(true);setError('');setNotice('');try{const value=JSON.parse(config);if(!value||Array.isArray(value)||typeof value!=='object')throw new Error('Profile 必须是 JSON 对象');const selected=profiles.find(p=>p.id===profileId);if(create){const p=await api<Profile>('/projects/'+projectId+'/profiles',{name:name||'新 Profile',config:value});setProfileId(p.id);}else await api('/profiles/'+profileId,{name,config:value,expected_version:selected?.version},'PUT');setNotice('Profile 已保存');onSaved();}catch(e){setError(errText(e));}finally{setWorking(false);}}
 return <Dialog title="模型与设置" onClose={onClose} wide><div className="tabs"><button className={tab==='model'?'active':''} onClick={()=>setTab('model')}>模型连接</button><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>项目 Profile</button></div>
 {tab==='model'&&settings?<div className="settings-form"><p className="muted">{cloudRuntime?'连接你的 HTTPS 模型服务。任务数据保存在此站点，所选上下文会发送给该模型服务。本机 Ollama 请使用本地部署版。':'使用本机 Ollama，或连接你自己的兼容模型服务。数据和文件保存在本机；选择远程模型时，任务上下文会发送给该服务。'}</p>{settings.environment_managed&&<p role="status" className="small-text">{cloudRuntime?'配置由云端环境变量管理。':'配置由 .env 或环境变量管理，修改后请重启服务。'}{settings.env_file&&<>配置文件：{settings.env_file}</>}</p>}<label>模型服务<select disabled={settings.environment_managed} value={settings.provider} onChange={e=>{const provider=e.target.value as Settings['provider'];setSettings({...settings,provider,base_url:cloudRuntime?(provider==='ollama'?'https://':'https://api.openai.com/v1'):(provider==='ollama'?'http://127.0.0.1:11434':'http://127.0.0.1:1234/v1'),model:'',has_api_key:false});setKey('');}}><option value="ollama">{cloudRuntime?'Ollama · HTTPS 服务':'Ollama · 本地模型'}</option><option value="openai">{cloudRuntime?'OpenAI 兼容接口 · HTTPS':'OpenAI 兼容接口 · 本地或远程'}</option></select></label><label>服务地址<input disabled={settings.environment_managed} value={settings.base_url} onChange={e=>setSettings({...settings,base_url:e.target.value})} spellCheck={false}/></label><label>模型名称<input disabled={settings.environment_managed} value={settings.model} onChange={e=>setSettings({...settings,model:e.target.value})} placeholder={settings.provider==='ollama'?'填写 ollama list 中已安装的模型名称':'填写服务支持的模型 ID'} spellCheck={false}/></label><label>单次请求超时（秒）<input type="number" min={5} max={3600} disabled={settings.environment_managed||settings.timeout_policy==='fixed_60_minutes'} value={settings.timeout_seconds} onChange={e=>setSettings({...settings,timeout_seconds:Number(e.target.value)})}/></label>{settings.timeout_policy==='fixed_60_minutes'&&<p className="muted small-text">模型请求超时统一为 60 分钟（3600 秒）；旧配置中的短超时也按此值执行。</p>}{(cloudRuntime||settings.provider==='openai')&&<><label>{cloudRuntime?'API Key':'API Key（本地服务可留空）'}<input disabled={settings.environment_managed} type="password" autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value)} placeholder={settings.has_api_key?'已保存，留空保留':'可选'}/></label>{settings.has_api_key&&<label className="check-label"><input disabled={settings.environment_managed} type="checkbox" checked={clearKey} onChange={e=>setClearKey(e.target.checked)}/>清除已保存的密钥</label>}</>}<p className="small-text muted">先启动模型服务。更换服务地址后，远程服务的密钥需要重新填写。</p><div className="dialog-actions">{!settings.environment_managed&&<button disabled={working} onClick={()=>saveModel()}><Save size={16}/>保存</button>}<button className="primary" disabled={working||!settings.model.trim()} onClick={()=>saveModel(true)}>{working?<Spinner/>:<PlugZap size={16}/>} {settings.environment_managed?'测试连接':'保存并测试连接'}</button></div></div>:tab==='model'?<Spinner/>:null}
 {tab==='profile'&&<div><p className="muted">{proposal?'AI 提出了下面的配置建议。请选择保存为新 Profile 或更新当前 Profile。':'控制生成语言、颗粒度、测试类型和附加业务规则。每次任务会保存配置快照。'}</p><label>选择 Profile<select value={profileId} onChange={e=>{const p=profiles.find(x=>x.id===e.target.value)!;setProfileId(p.id);setName(p.name);if(!proposal)setConfig(JSON.stringify(p.config,null,2));}}>{profiles.map(p=><option key={p.id} value={p.id}>{p.name} · v{p.version}</option>)}</select></label><label>Profile 名称<input value={name} onChange={e=>setName(e.target.value)}/></label><label>配置 JSON<textarea className="code-editor profile-editor" aria-label="Profile 配置 JSON" value={config} onChange={e=>setConfig(e.target.value)} spellCheck={false}/></label><div className="dialog-actions"><button disabled={working} onClick={()=>saveProfile(true)}><Plus size={16}/>保存为新 Profile</button><button className="primary" disabled={working||!profileId} onClick={()=>saveProfile(false)}>{working?<Spinner/>:<Save size={16}/>}更新当前 Profile</button></div></div>}
 <ErrorBox message={error}/>{notice&&<p role="status" className="success inline"><Check size={16}/>{notice}</p>}</Dialog>;
}
