import {useEffect,useState} from 'react';
import {api,errText} from './api';
import {ErrorBox,Spinner,TextValue} from './ui';
import type {Json} from './types';

export function WorkspaceCoverage({artifactId,revision,artifactType,initialData,initialOpen=false,showFreshness=true}:{showFreshness?:boolean;initialData?:Json;initialOpen?:boolean;artifactId:string;revision:number;artifactType?:string}){
 const [open,setOpen]=useState(initialOpen);const [loadedWorkspace,setLoadedWorkspace]=useState<Json>();const [branch,setBranch]=useState('');const [error,setError]=useState('');const [attempt,setAttempt]=useState(0);
 const snapshot=initialData!==undefined;
 const workspace=snapshot?initialData:loadedWorkspace;
 const data=workspace?.coverage??(snapshot?initialData:undefined);
 useEffect(()=>{setBranch('');},[artifactId]);
 useEffect(()=>{if(snapshot||!open)return;let alive=true;setLoadedWorkspace(undefined);setError('');api<Json>('/artifacts/'+artifactId+'/workspace'+(branch?'?case_artifact_id='+encodeURIComponent(branch):'')).then(value=>{if(alive)setLoadedWorkspace(value);}).catch(e=>{if(alive)setError(errText(e));});return()=>{alive=false;};},[open,artifactId,revision,attempt,branch,snapshot]);
 const totals=data?.totals??{};
 return <div className="workspace-coverage"><button className="text-accent" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'收起覆盖关系':'查看需求 → 场景 → 用例覆盖'}</button>{open&&<section aria-label="场景和用例覆盖"><ErrorBox message={error}/>{error&&<button onClick={()=>setAttempt(x=>x+1)}>重新读取覆盖</button>}{!data&&!error&&<p className="muted inline"><Spinner/>正在读取覆盖关系…</p>}{data&&<>{!snapshot&&artifactType==='scenarios'&&(workspace?.related_artifacts??[]).filter((item:Json)=>item.type==='cases'&&item.linked).length>1&&<label>覆盖统计使用的用例成果<select aria-label="覆盖统计使用的用例成果" value={branch} onChange={e=>setBranch(e.target.value)}><option value="">最新关联用例</option>{workspace?.related_artifacts.filter((item:Json)=>item.type==='cases'&&item.linked).map((item:Json)=><option key={item.id} value={item.id}>{item.title} · v{item.revision}</option>)}</select></label>}{showFreshness&&workspace?.stale?.scenarios&&<p className="coverage-gap">场景已更新，关联用例仍基于较早版本。可预览同步关联用例。{workspace.stale.changed_scenario_ids?.length?' 变更场景：'+workspace.stale.changed_scenario_ids.join('、'):''}</p>}{showFreshness&&workspace?.stale?.analysis&&<p className="coverage-gap">需求理解已更新，关联成果仍基于较早版本，请核对影响。</p>}<div className="coverage-metrics"><span><strong>{totals.requirements_with_scenarios??0} / {totals.requirements??0}</strong>需求已有场景</span><span><strong>{totals.requirements_with_cases??0} / {totals.requirements??0}</strong>需求已有用例</span><span><strong>{totals.scenarios_with_cases??0} / {totals.scenarios??0}</strong>场景已有用例</span><span><strong>{totals.cases??0}</strong>用例总数</span></div><p className="muted small-text">按当前关联成果及稳定编号统计结构覆盖；已有用例不代表与最新需求一致，也不代表已执行通过。</p><div className="table-scroll"><table><thead><tr><th>场景</th><th>关联用例</th><th>数量</th><th>覆盖情况</th></tr></thead><tbody>{(data.scenarios??[]).map((item:Json)=><tr key={(item.artifact_id??'')+':'+item.id}><td>{item.id} · {item.title}</td><td>{(item.case_ids??[]).join('、')||'—'}</td><td>{item.case_count??item.case_ids?.length??0}</td><td>{item.case_count||item.case_ids?.length?'已有用例':'待补用例'}{item.status==='excluded'?'（范围排除）':''}</td></tr>)}</tbody></table></div>{!(data.scenarios??[]).length&&<p className="muted">尚无关联场景。</p>}<details><summary>逐项需求覆盖 · {totals.requirements??0}</summary><div className="table-scroll"><table><thead><tr><th>需求</th><th>场景编号</th><th>用例编号</th></tr></thead><tbody>{(data.requirements??[]).map((item:Json)=><tr key={item.id}><td>{item.id} · {item.title}</td><td>{(item.scenario_ids??[]).join('、')||'待补场景'}</td><td>{(item.case_ids??[]).join('、')||'待补用例'}</td></tr>)}</tbody></table></div></details>{(data.orphan_cases??[]).length>0&&<p className="coverage-gap">未找到关联场景的用例：{data.orphan_cases.map((item:Json|string)=>typeof item==='string'?item:item.id??item.case_id).join('、')}</p>}{(data.notes??[]).map((note:unknown,index:number)=><p className="muted small-text" key={index}><TextValue value={note}/></p>)}</>}</section>}</div>;
}
